/* Cdocs // index-aux-min.js - Javascript. // Archivo 'auxiliar' para index.js (Comprimido con Google Closure Compiler).Versión 0.1.0.Fecha de edición/revisión: 31/01/2016. Foog.Software. Licencia MIT. */
String.prototype.capitalizarPrimeraLetra=function(){return this.charAt(0).toUpperCase()+this.slice(1)};
function buscarTipoNIF(b){var a=[],c="";a.A="Sociedades an\u00f3nimas.";a.B="Sociedades de responsabilidad limitada.";a.C="Sociedades colectivas.";a.D="Sociedades comanditarias.";a.E="Comunidades de bienes y herencias yacentes.";a.F="Sociedades cooperativas.";a.G="Asociaciones y otros tipos de sociedades civiles.";a.H="Comunidades de propietarios en r\u00e9gimen de propiedad horizontal.";a.I="El NIF para los nacionales con DNI carece de letra inicial y coincide con este \u00faltimo documento.";a.J=
"Sociedades civiles; con o sin personalidad jur\u00eddica.";a.K="NIF para espa\u00f1oles menores de 14 a\u00f1os que carezcan de DNI o extranjeros menores de 18 a\u00f1os que carezcan de NIE.";a.L="NIF para espa\u00f1oles mayores de 14 a\u00f1os residentes en el extranjero y que no tengan DNI.";a.M="NIF para extranjeros que sean miembros de embajadas u otros organismos internacionales acreditados en Espa\u00f1a.";a.N="Entidades extranjeras; no residentes en Espa\u00f1a.";a.P="Corporaci\u00f3nes locales.";
a.Q="Organismos aut\u00f3nomos; estatales o no; y asimilados; y congregaciones e instituciones religiosas.";a.R="Congregaciones e instituciones religiosas.";a.S="Organos de la Administraci\u00f3n del Estado y comunidades aut\u00f3nomas.";a.U="Uniones temporales de empresas.";a.V="Fondos de inversiones y otros tipos no definidos en el resto de claves.";a.X="NIF para extranjeros residentes; con NIE asignado antes del 16 de julio de 2008.";a.Y="NIF para extranjeros residentes; con NIE asignado despu\u00e9s del 16 de julio de 2008.";
a.Z="NIF para extranjeros residentes; con NIE asignado despu\u00e9s del 16 de julio de 2008.";a.W="Reservado a establecimientos permanentes de entidades no residentes en territorio espa\u00f1ol.";return c=a[b]?a[b]:"DESCONOCIDO"}
function obtenerPaises(b,a){a=a?a.toLowerCase():"es";var c,d;switch(a){case "es":d=0;c="desconocido";break;case "en":d=1;c="unknown";break;case "fr":d=2;c="inconnu";break;default:d=0,c="desconocido"}var e={AF:["Afganist\u00e1n","Afghanistan","Afghanistan"],AL:["Albania","Albania","Albanie"],DE:["Alemania","Germany","Allemagne"],DZ:["Algeria","Algeria","Alg\u00e9rie"],AD:["Andorra","Andorra","Andorra"],AO:["Angola","Angola","Angola"],AI:["Anguila","Anguilla","Anguilla"],AQ:["Ant\u00e1rtida","Antarctica",
"L'Antarctique"],AG:["Antigua y Barbuda","Antigua and Barbuda","Antigua et Barbuda"],AN:["Antillas Neerlandesas","Netherlands Antilles","Antilles N\u00e9erlandaises"],SA:["Arabia Saudita","Saudi Arabia","Arabie Saoudite"],AR:["Argentina","Argentina","Argentine"],AM:["Armenia","Armenia","L'Arm\u00e9nie"],AW:["Aruba","Aruba","Aruba"],AU:["Australia","Australia","Australie"],AT:["Austria","Austria","Autriche"],AZ:["Azerbay\u00e1n","Azerbaijan","L'Azerba\u00efdjan"],BE:["B\u00e9lgica","Belgium","Belgique"],
BS:["Bahamas","Bahamas","Bahamas"],BH:["Bahrein","Bahrain","Bahre\u00efn"],BD:["Bangladesh","Bangladesh","Bangladesh"],BB:["Barbados","Barbados","Barbade"],BZ:["Belice","Belize","Belize"],BJ:["Ben\u00edn","Benin","B\u00e9nin"],BT:["Bhut\u00e1n","Bhutan","Le Bhoutan"],BY:["Bielorrusia","Belarus","Bi\u00e9lorussie"],MM:["Birmania","Myanmar","Myanmar"],BO:["Bolivia","Bolivia","Bolivie"],BA:["Bosnia y Herzegovina","Bosnia and Herzegovina","Bosnie-Herz\u00e9govine"],BW:["Botsuana","Botswana","Botswana"],
BR:["Brasil","Brazil","Br\u00e9sil"],BN:["Brun\u00e9i","Brunei","Brunei"],BG:["Bulgaria","Bulgaria","Bulgarie"],BF:["Burkina Faso","Burkina Faso","Burkina Faso"],BI:["Burundi","Burundi","Burundi"],CV:["Cabo Verde","Cape Verde","Cap-Vert"],KH:["Camboya","Cambodia","Cambodge"],CM:["Camer\u00fan","Cameroon","Cameroun"],CA:["Canad\u00e1","Canada","Canada"],TD:["Chad","Chad","Tchad"],CL:["Chile","Chile","Chili"],CN:["China","China","Chine"],CY:["Chipre","Cyprus","Chypre"],VA:["Ciudad del Vaticano","Vatican City State",
"Cit\u00e9 du Vatican"],CO:["Colombia","Colombia","Colombie"],KM:["Comoras","Comoros","Comores"],CG:["Congo","Congo","Congo"],CD:["Congo","Congo","Congo"],KP:["Corea del Norte","North Korea","Cor\u00e9e du Nord"],KR:["Corea del Sur","South Korea","Cor\u00e9e du Sud"],CI:["Costa de Marfil","Ivory Coast","C\u00f4te-d'Ivoire"],CR:["Costa Rica","Costa Rica","Costa Rica"],HR:["Croacia","Croatia","Croatie"],CU:["Cuba","Cuba","Cuba"],DK:["Dinamarca","Denmark","Danemark"],DM:["Dominica","Dominica","Dominique"],
EC:["Ecuador","Ecuador","Equateur"],EG:["Egipto","Egypt","Egypte"],SV:["El Salvador","El Salvador","El Salvador"],AE:["Emiratos \u00c1rabes Unidos","United Arab Emirates","Emirats Arabes Unis"],ER:["Eritrea","Eritrea","Erythr\u00e9e"],SK:["Eslovaquia","Slovakia","Slovaquie"],SI:["Eslovenia","Slovenia","Slov\u00e9nie"],ES:["Espa\u00f1a","Spain","Espagne"],US:["Estados Unidos de Am\u00e9rica","United States of America","\u00c9tats-Unis d'Am\u00e9rique"],EE:["Estonia","Estonia","L'Estonie"],ET:["Etiop\u00eda",
"Ethiopia","Ethiopie"],PH:["Filipinas","Philippines","Philippines"],FI:["Finlandia","Finland","Finlande"],FJ:["Fiyi","Fiji","Fidji"],FR:["Francia","France","France"],GA:["Gab\u00f3n","Gabon","Gabon"],GM:["Gambia","Gambia","Gambie"],GE:["Georgia","Georgia","G\u00e9orgie"],GH:["Ghana","Ghana","Ghana"],GI:["Gibraltar","Gibraltar","Gibraltar"],GD:["Granada","Grenada","Grenade"],GR:["Grecia","Greece","Gr\u00e8ce"],GL:["Groenlandia","Greenland","Groenland"],GP:["Guadalupe","Guadeloupe","Guadeloupe"],GU:["Guam",
"Guam","Guam"],GT:["Guatemala","Guatemala","Guatemala"],GF:["Guayana Francesa","French Guiana","Guyane fran\u00e7aise"],GG:["Guernsey","Guernsey","Guernesey"],GN:["Guinea","Guinea","Guin\u00e9e"],GQ:["Guinea Ecuatorial","Equatorial Guinea","Guin\u00e9e Equatoriale"],GW:["Guinea-Bissau","Guinea-Bissau","Guin\u00e9e-Bissau"],GY:["Guyana","Guyana","Guyane"],HT:["Hait\u00ed","Haiti","Ha\u00efti"],HN:["Honduras","Honduras","Honduras"],HK:["Hong kong","Hong Kong","Hong Kong"],HU:["Hungr\u00eda","Hungary",
"Hongrie"],IN:["India","India","Inde"],ID:["Indonesia","Indonesia","Indon\u00e9sie"],IR:["Ir\u00e1n","Iran","Iran"],IQ:["Irak","Iraq","Irak"],IE:["Irlanda","Ireland","Irlande"],BV:["Isla Bouvet","Bouvet Island","Bouvet Island"],IM:["Isla de Man","Isle of Man","Ile de Man"],CX:["Isla de Navidad","Christmas Island","Christmas Island"],NF:["Isla Norfolk","Norfolk Island","\u00cele de Norfolk"],IS:["Islandia","Iceland","Islande"],BM:["Islas Bermudas","Bermuda Islands","Bermudes"],KY:["Islas Caim\u00e1n",
"Cayman Islands","Iles Ca\u00efmans"],CC:["Islas Cocos (Keeling)","Cocos (Keeling) Islands","Cocos (Keeling"],CK:["Islas Cook","Cook Islands","Iles Cook"],AX:["Islas de \u00c5land","\u00c5land Islands","\u00celes \u00c5land"],FO:["Islas Feroe","Faroe Islands","Iles F\u00e9ro"],GS:["Islas Georgias del Sur y Sandwich del Sur","South Georgia and the South Sandwich Islands","G\u00e9orgie du Sud et les \u00celes Sandwich du Sud"],HM:["Islas Heard y McDonald","Heard Island and McDonald Islands","Les \u00eeles Heard et McDonald"],
MV:["Islas Maldivas","Maldives","Maldives"],FK:["Islas Malvinas","Falkland Islands (Malvinas)","Iles Falkland (Malvinas"],MP:["Islas Marianas del Norte","Northern Mariana Islands","Iles Mariannes du Nord"],MH:["Islas Marshall","Marshall Islands","Iles Marshall"],PN:["Islas Pitcairn","Pitcairn Islands","Iles Pitcairn"],SB:["Islas Salom\u00f3n","Solomon Islands","Iles Salomon"],TC:["Islas Turcas y Caicos","Turks and Caicos Islands","Iles Turques et Ca\u00efques"],UM:["Islas Ultramarinas Menores de Estados Unidos",
"United States Minor Outlying Islands","\u00c9tats-Unis \u00celes mineures \u00e9loign\u00e9es"],VG:["Islas V\u00edrgenes Brit\u00e1nicas","Virgin Islands","Iles Vierges"],VI:["Islas V\u00edrgenes de los Estados Unidos","United States Virgin Islands","\u00celes Vierges am\u00e9ricaines"],IL:["Israel","Israel","Isra\u00ebl"],IT:["Italia","Italy","Italie"],JM:["Jamaica","Jamaica","Jama\u00efque"],JP:["Jap\u00f3n","Japan","Japon"],JE:["Jersey","Jersey","Maillot"],JO:["Jordania","Jordan","Jordan"],KZ:["Kazajist\u00e1n",
"Kazakhstan","Le Kazakhstan"],KE:["Kenia","Kenya","Kenya"],KG:["Kirgizst\u00e1n","Kyrgyzstan","Kirghizstan"],KI:["Kiribati","Kiribati","Kiribati"],KW:["Kuwait","Kuwait","Kowe\u00eft"],LB:["L\u00edbano","Lebanon","Liban"],LA:["Laos","Laos","Laos"],LS:["Lesoto","Lesotho","Lesotho"],LV:["Letonia","Latvia","La Lettonie"],LR:["Liberia","Liberia","Liberia"],LY:["Libia","Libya","Libye"],LI:["Liechtenstein","Liechtenstein","Liechtenstein"],LT:["Lituania","Lithuania","La Lituanie"],LU:["Luxemburgo","Luxembourg",
"Luxembourg"],MX:["M\u00e9xico","Mexico","Mexique"],MC:["M\u00f3naco","Monaco","Monaco"],MO:["Macao","Macao","Macao"],MK:["Maced\u00f4nia","Macedonia","Mac\u00e9doine"],MG:["Madagascar","Madagascar","Madagascar"],MY:["Malasia","Malaysia","Malaisie"],MW:["Malawi","Malawi","Malawi"],ML:["Mali","Mali","Mali"],MT:["Malta","Malta","Malte"],MA:["Marruecos","Morocco","Maroc"],MQ:["Martinica","Martinique","Martinique"],MU:["Mauricio","Mauritius","Iles Maurice"],MR:["Mauritania","Mauritania","Mauritanie"],
YT:["Mayotte","Mayotte","Mayotte"],FM:["Micronesia","Estados Federados de","Federados Estados de"],MD:["Moldavia","Moldova","Moldavie"],MN:["Mongolia","Mongolia","Mongolie"],ME:["Montenegro","Montenegro","Mont\u00e9n\u00e9gro"],MS:["Montserrat","Montserrat","Montserrat"],MZ:["Mozambique","Mozambique","Mozambique"],NA:["Namibia","Namibia","Namibie"],NR:["Nauru","Nauru","Nauru"],NP:["Nepal","Nepal","N\u00e9pal"],NI:["Nicaragua","Nicaragua","Nicaragua"],NE:["Niger","Niger","Niger"],NG:["Nigeria","Nigeria",
"Nigeria"],NU:["Niue","Niue","Niou"],NO:["Noruega","Norway","Norv\u00e8ge"],NC:["Nueva Caledonia","New Caledonia","Nouvelle-Cal\u00e9donie"],NZ:["Nueva Zelanda","New Zealand","Nouvelle-Z\u00e9lande"],OM:["Om\u00e1n","Oman","Oman"],NL:["Pa\u00edses Bajos","Netherlands","Pays-Bas"],PK:["Pakist\u00e1n","Pakistan","Pakistan"],PW:["Palau","Palau","Palau"],PS:["Palestina","Palestine","La Palestine"],PA:["Panam\u00e1","Panama","Panama"],PG:["Pap\u00faa Nueva Guinea","Papua New Guinea","Papouasie-Nouvelle-Guin\u00e9e"],
PY:["Paraguay","Paraguay","Paraguay"],PE:["Per\u00fa","Peru","P\u00e9rou"],PF:["Polinesia Francesa","French Polynesia","Polyn\u00e9sie fran\u00e7aise"],PL:["Polonia","Poland","Pologne"],PT:["Portugal","Portugal","Portugal"],PR:["Puerto Rico","Puerto Rico","Porto Rico"],QA:["Qatar","Qatar","Qatar"],GB:["Reino Unido","United Kingdom","Royaume-Uni"],CF:["Rep\u00fablica Centroafricana","Central African Republic","R\u00e9publique Centrafricaine"],CZ:["Rep\u00fablica Checa","Czech Republic","R\u00e9publique Tch\u00e8que"],
DO:["Rep\u00fablica Dominicana","Dominican Republic","R\u00e9publique Dominicaine"],RE:["Reuni\u00f3n","R\u00e9union","R\u00e9union"],RW:["Ruanda","Rwanda","Rwanda"],RO:["Ruman\u00eda","Romania","Roumanie"],RU:["Rusia","Russia","La Russie"],EH:["Sahara Occidental","Western Sahara","Sahara Occidental"],WS:["Samoa","Samoa","Samoa"],AS:["Samoa Americana","American Samoa","Les Samoa am\u00e9ricaines"],BL:["San Bartolom\u00e9","Saint Barth\u00e9lemy","Saint-Barth\u00e9lemy"],KN:["San Crist\u00f3bal y Nieves",
"Saint Kitts and Nevis","Saint Kitts et Nevis"],SM:["San Marino","San Marino","San Marino"],MF:["San Mart\u00edn (Francia)","Saint Martin (French part)","Saint-Martin (partie fran\u00e7aise)"],PM:["San Pedro y Miquel\u00f3n","Saint Pierre and Miquelon","Saint-Pierre-et-Miquelon"],VC:["San Vicente y las Granadinas","Saint Vincent and the Grenadines","Saint-Vincent et Grenadines"],SH:["Santa Elena","Ascensi\u00f3n y Trist\u00e1n de Acu\u00f1a","Ascensi\u00f3n y Tristan de Acu\u00f1a"],LC:["Santa Luc\u00eda",
"Saint Lucia","Sainte-Lucie"],ST:["Santo Tom\u00e9 y Pr\u00edncipe","Sao Tome and Principe","Sao Tom\u00e9 et Principe"],SN:["Senegal","Senegal","S\u00e9n\u00e9gal"],RS:["Serbia","Serbia","Serbie"],SC:["Seychelles","Seychelles","Les Seychelles"],SL:["Sierra Leona","Sierra Leone","Sierra Leone"],SG:["Singapur","Singapore","Singapour"],SY:["Siria","Syria","Syrie"],SO:["Somalia","Somalia","Somalie"],LK:["Sri lanka","Sri Lanka","Sri Lanka"],ZA:["Sud\u00e1frica","South Africa","Afrique du Sud"],SD:["Sud\u00e1n",
"Sudan","Soudan"],SE:["Suecia","Sweden","Su\u00e8de"],CH:["Suiza","Switzerland","Suisse"],SR:["Surin\u00e1m","Suriname","Surinam"],SJ:["Svalbard y Jan Mayen","Svalbard and Jan Mayen","Svalbard et Jan Mayen"],SZ:["Swazilandia","Swaziland","Swaziland"],TJ:["Tadjikist\u00e1n","Tajikistan","Le Tadjikistan"],TH:["Tailandia","Thailand","Tha\u00eflande"],TW:["Taiw\u00e1n","Taiwan","Taiwan"],TZ:["Tanzania","Tanzania","Tanzanie"],IO:["Territorio Brit\u00e1nico del Oc\u00e9ano \u00cdndico","British Indian Ocean Territory",
"Territoire britannique de l'oc\u00e9an Indien"],TF:["Territorios Australes y Ant\u00e1rticas Franceses","French Southern Territories","Terres australes fran\u00e7aises"],TL:["Timor Oriental","East Timor","Timor-Oriental"],TG:["Togo","Togo","Togo"],TK:["Tokelau","Tokelau","Tok\u00e9laou"],TO:["Tonga","Tonga","Tonga"],TT:["Trinidad y Tobago","Trinidad and Tobago","Trinidad et Tobago"],TN:["Tunez","Tunisia","Tunisie"],TM:["Turkmenist\u00e1n","Turkmenistan","Le Turkm\u00e9nistan"],TR:["Turqu\u00eda",
"Turkey","Turquie"],TV:["Tuvalu","Tuvalu","Tuvalu"],UA:["Ucrania","Ukraine","L'Ukraine"],UG:["Uganda","Uganda","Ouganda"],UY:["Uruguay","Uruguay","Uruguay"],UZ:["Uzbekist\u00e1n","Uzbekistan","L'Ouzb\u00e9kistan"],VU:["Vanuatu","Vanuatu","Vanuatu"],VE:["Venezuela","Venezuela","Venezuela"],VN:["Vietnam","Vietnam","Vietnam"],WF:["Wallis y Futuna","Wallis and Futuna","Wallis et Futuna"],YE:["Yemen","Yemen","Y\u00e9men"],DJ:["Yibuti","Djibouti","Djibouti"],ZM:["Zambia","Zambia","Zambie"],ZW:["Zimbabue",
"Zimbabwe","Zimbabwe"]};e.hasOwnProperty(b)&&(c=e[b][d]);return c}
function obtenerProvincia(b){b=1===b.length?"0"+b:b.toString();var a={"01":"\u00c1lava","02":"Albacete","03":"Alicante","04":"Almer\u00eda","05":"\u00c1vila","06":"Badajoz","07":"Islas Baleares","08":"Barcelona","09":"Burgos",10:"C\u00e1ceres",11:"C\u00e1diz",12:"Castell\u00f3n",13:"Ciudad Real",14:"C\u00f3rdoba",15:"A Coru\u00f1a",16:"Cuenca",17:"Girona",18:"Granada",19:"Guadalajara",20:"Guip\u00fazcoa",21:"Huelva",22:"Huesca",23:"Ja\u00e9n",24:"Le\u00f3n",25:"Lleida",26:"La Rioja",27:"Lugo",28:"Madrid",
29:"M\u00e1laga",30:"Murcia",31:"Navarra",32:"Orense",33:"Asturias",34:"Palencia",35:"Las Palmas",36:"Pontevedra",37:"Salamanca",38:"Santa Cruz de Tenerife",39:"Cantabria",40:"Segovia",41:"Sevilla",42:"Soria",43:"Tarragona",44:"Teruel",45:"Toledo",46:"Valencia",47:"Valladolid",48:"Vizcaya",49:"Zamora",50:"Zaragoza",51:"Ceuta",52:"Melilla",53:"Alicante",54:"Alicante",55:"Girona",56:"C\u00f3rdoba",57:"Islas Baleares",58:"Barcelona",59:"Barcelona",60:"Barcelona",61:"Barcelona",62:"Barcelona",63:"Barcelona",
64:"Barcelona",70:"A Coru\u00f1a",71:"Guip\u00fazcoa",72:"C\u00e1diz",73:"Murcia",74:"Asturias",75:"Santa Cruz de Tenerife",76:"Las Palmas",77:"Tarragona",78:"Madrid",79:"Madrid",80:"Madrid",81:"Madrid",82:"Madrid",83:"Madrid",84:"Madrid",85:"Madrid",91:"Sevilla",92:"M\u00e1laga",93:"M\u00e1laga",94:"Pontevedra",95:"Vizcaya",96:"Valencia",97:"Valencia",98:"Valencia",99:"Zaragoza"};return a.hasOwnProperty(b)?a[b]:"DESCONOCIDA"}
function documentarErrorAJAX(b){var a=b.toString().eliminarEspaciosEnBlanco().substr(0,3),c={400:"Bad Request",401:"Unauthorized",403:"Forbidden",404:"Not Found",405:"Method Not Allowed",406:"Not Acceptable",407:"Proxy Authentication Required",408:"Request Timeout",409:"Conflict",410:"Gone(NotFound)",411:"Length Required",412:"Precondition Failed",413:"Request Entity Too Large",414:"Request-URI Too Long",415:"Unsupported Media Type",416:"Requested Range Not Suitable",417:"Expectation Failed",422:"Unprocessable Entity",
423:"Locked",424:"Falied Dependency",425:"Unassigned",426:"Upgrade Required",428:"Precondition Required",429:"Too Many Requests",431:"Request Headers Fileds Too Large",449:"The request should be retried after doing the appropriate action",451:"Unavailable for Legal Reasons",500:"Internal Server Error",501:"Not Implemented",502:"Bad Gateway",503:"Service Unavailable",504:"Gateway Timeout",505:"HTTP Version Not Supported",506:"Variant Also Negotiates",507:"Insufficient Storage",508:"Loop Detected",
509:"Limit Bandwidth Exceeded",510:"Not Extended",511:"Network Authentication Required",512:"Invalid XML format"};if(c.hasOwnProperty(a))return"Error "+a+" : "+c[a];if(!1===isNaN(a))return"Error "+a+" : Unknown";if(""===b)return"Error : Unknown";"object"===typeof b&&b.message&&(b=b.message);"string"===typeof b&&72<b.length&&(b=b.substr(0,68)+" ...");return b}
function documentarIdioma(b){b=b.toLowerCase();var a={aa:"afar",ab:"abjasio (o abjasiano)",ae:"av\u00e9stico",af:"afrik\u00e1ans",ak:"akano",am:"amh\u00e1rico",an:"aragon\u00e9s",ar:"\u00e1rabe",as:"asam\u00e9s",av:"avar (o \u00e1varo)",ay:"aimara",az:"azer\u00ed",ba:"baskir",be:"bielorruso",bg:"b\u00falgaro",bh:"bhoyapur\u00ed",bi:"bislama",bm:"bambara",bn:"bengal\u00ed",bo:"tibetano",br:"bret\u00f3n",bs:"bosnio",ca:"catal\u00e1n",ce:"checheno",ch:"chamorro",co:"corso",cr:"cree",cs:"checo",cu:"eslavo eclesi\u00e1stico antiguo",
cv:"chuvasio",cy:"gal\u00e9s",da:"dan\u00e9s",de:"alem\u00e1n",dv:"maldivo (o dhivehi)",dz:"dzongkha",ee:"ew\u00e9",el:"griego (moderno)",en:"ingl\u00e9s",eo:"esperanto",es:"espa\u00f1ol (o castellano)",et:"estonio",eu:"euskera",fa:"persa",ff:"fula",fi:"fin\u00e9s (o finland\u00e9s)",fj:"fiyiano (o fiyi)",fo:"fero\u00e9s",fr:"franc\u00e9s",fy:"fris\u00f3n (o frisio)",ga:"irland\u00e9s (o ga\u00e9lico)",gd:"ga\u00e9lico escoc\u00e9s",gl:"gallego",gn:"guaran\u00ed",gu:"guyarat\u00ed (o guyarat\u00ed)",
gv:"man\u00e9s (ga\u00e9lico man\u00e9s o de Isla de Man)",ha:"hausa",he:"hebreo",hi:"hindi (o hind\u00fa)",ho:"hiri motu",hr:"croata",ht:"haitiano",hu:"h\u00fangaro",hy:"armenio",hz:"herero",ia:"interlingua",id:"indonesio",ie:"occidental",ig:"igbo",ii:"yi de Sichu\u00e1n",ik:"i\u00f1upiaq",io:"ido",is:"island\u00e9s",it:"italiano",iu:"inuktitut (o inuit)",ja:"japon\u00e9s",jv:"javan\u00e9s",ka:"georgiano",kg:"kongo (o kikongo)",ki:"kikuyu",kj:"kuanyama",kk:"kazajo (o kazajio)",kl:"groenland\u00e9s (o kalaallisut)",
km:"camboyano (o jemer)",kn:"canar\u00e9s",ko:"coreano",kr:"kanuri",ks:"cachemiro (o cachemir)",ku:"kurdo",kv:"komi",kw:"c\u00f3rnico",ky:"kirgu\u00eds",la:"lat\u00edn",lb:"luxemburgu\u00e9s",lg:"luganda",li:"limburgu\u00e9s",ln:"lingala",lo:"lao",lt:"lituano",lu:"luba-katanga (o chiluba)",lv:"let\u00f3n",mg:"malgache (o malagasy)",mh:"marshal\u00e9s",mi:"maor\u00ed",mk:"macedonio",ml:"malayalam",mn:"mongol",mr:"marat\u00ed",ms:"malayo",mt:"malt\u00e9s",my:"birmano",na:"nauruano",nb:"noruego bokm\u00e5l",
nd:"ndebele del norte",ne:"nepal\u00ed",ng:"ndonga",nl:"neerland\u00e9s (u holand\u00e9s)",nn:"nynorsk",no:"noruego",nr:"ndebele del sur",nv:"navajo",ny:"chichewa",oc:"occitano",oj:"ojibwa",om:"oromo",or:"oriya",os:"os\u00e9tico (u osetio, u oseta)",pa:"panyab\u00ed (o penyabi)",pi:"pali",pl:"polaco",ps:"past\u00fa (o past\u00fan, o pashto)",pt:"portugu\u00e9s",qu:"quechua",rm:"romanche",rn:"kirundi",ro:"rumano",ru:"ruso",rw:"ruand\u00e9s (o ki\u00f1aruanda)",sa:"s\u00e1nscrito",sc:"sardo",sd:"sindhi",
se:"sami septentrional",sg:"sango",si:"cingal\u00e9s",sk:"eslovaco",sl:"esloveno",sm:"samoano",sn:"shona",so:"somal\u00ed",sq:"alban\u00e9s",sr:"serbio",ss:"suazi (o swati, o siSwati)",st:"sesotho",su:"sundan\u00e9s (o sondan\u00e9s)",sv:"sueco",sw:"suajili",ta:"tamil",te:"t\u00e9lugu",tg:"tayiko",th:"tailand\u00e9s",ti:"tigri\u00f1a",tk:"turcomano",tl:"tagalo",tn:"setsuana",to:"tongano",tr:"turco",ts:"tsonga",tt:"t\u00e1rtaro",tw:"twi",ty:"tahitiano",ug:"uigur",uk:"ucraniano",ur:"urdu",uz:"uzbeko",
ve:"venda",vi:"vietnamita",vo:"volap\u00fck",wa:"val\u00f3n",wo:"wolof",xh:"xhosa",yi:"y\u00eddish (o yidis, o yiddish)",yo:"yoruba",za:"chuan (o chuang, o zhuang)",zh:"chino",zu:"zul\u00fa"};return a.hasOwnProperty(b)?a[b]:"undefined"};
