/* Cdocs // index-min.js - Javascript Versión 0.1.0. Fecha de edición/revisión: 31/01/2016. Foog.Software. Dependencias Javascript: AIRAliases-min.js, AIRSourceViewer-min.js, alivePDFgenerator-min.js, alivePDFWrapper-min.js, humane-min.js, iban-min.js, index-aux-min.js. Dependencias SWF: servicemonitor.swf, alivePDFlib.swf. Licencia MIT. */
var fechaSistema,formularios="home iban ccc ntc nif dni nie naf cccss update about download".split(" "),botones=["botones-mnu","botones-inicio","botones-nuevo","botones-imprimir","botones-validar"],teclasRestringidas=[8,9,16,17,18,19,20,27,34,35,36,37,38,39,40,44,45,46],errorValidar=!1,errorAJAX=!1,plantillaAlertaEspera="<span><img src='images/gear_14.png' alt='' title='' class='alerta-imagen-info'></span><span class='alerta-texto-info'> ... creando archivo PDF. Un momento por favor.</span></span>",
plantillaAlertaInfo="<span><img src='images/info_14.png' alt='' title='' class='alerta-imagen-info'></span><span class='alerta-texto-info'> ... pulsa &#171;IM<u>P</u>RIMIR&#187; para m\u00e1s detalles (PDF).</span></span>",formularioActivo="",urlEntidad="",formularioValorOculto="",erroresIBAN,contador=0,transferencia,solicitud,almacenamientoDescarga="",matrizBytes,actualizacionesTarea="",procesandoActualizaciones=!1,precargarImagen=function(){(new Image).src="images/giro_48.gif"},protector={activo:!1,
abrir:function(){this.activo=!0;document.getElementById("protector").style.display="block";document.getElementById("protector-imagen").style.display="block"},cerrar:function(){this.activo=!1;document.getElementById("protector-imagen").style.display="none";document.getElementById("protector").style.display="none"}},ventanaPrincipalMinimizada=!1,mnuEmergente,monitor,internetDisponible=!1,propiedadesPrograma={versiones:{larga:"",corta:"",tipo:"",actualizaciones:"",actualizacionesMensaje:"",actualizacionesError:"",
actualizacionesDisponibles:!1,actualizacionesPeso:0,actualizacionesDescriptor:"http://www.foog.es/download/air/cdocs/updateDescriptor.xml",actualizacionesAlmacenamiento:"",actualizacionesRepositorio:"",actualizacionesPaquete:""},tirada:"Marzo 2016",serie:"FHYG-N2XS-6GM6",identificador:"",nombre:"cdocs",baseDatosFecha:"Diciembre 2015"},propiedadesEquipo={tipo:air.Capabilities.playerType,sistemaOperativo:air.Capabilities.os,sistemaOperativoNombreComercial:"",sistemaOperativoNombreInterno:"",sistemaOperativoAlias:/^mac/i.test(air.Capabilities.os)?
"mac":/^win/i.test(air.Capabilities.os)?"win":/^linux/i.test(air.Capabilities.os)?"lnx":/^and/i.test(air.Capabilities.os)?"and":/^iphone/i.test(air.Capabilities.os)?"iph":"otros",idioma:"undefined"===documentarIdioma(air.Capabilities.language)?air.Capabilities.language:"<span>"+air.Capabilities.language+"</span><span></span>&#160;&#8212;&#160;<span>"+documentarIdioma(air.Capabilities.language).capitalizarPrimeraLetra()+"</span>",pantalla:air.Capabilities.screenResolutionX+" x "+air.Capabilities.screenResolutionY+
" p\u00edxeles",inputMethodEditor:air.Capabilities.hasIME,motorAIR:air.NativeApplication.nativeApplication.runtimeVersion,motorAIRcomercial:air.NativeApplication.nativeApplication.runtimeVersion.match(/\d+\.\d+/)[0],visorPDF:"",flashPlayer:air.Capabilities.version,webkit:navigator.userAgent&&null!==navigator.userAgent.match(/applewebkit\/(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)/ig)?navigator.userAgent.match(/applewebkit\/(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)/ig)[0].replace(/applewebkit\//i,""):" ... "};
String.prototype.eliminarEspaciosEnBlanco=function(){return this.replace(/(?:(?:^|\n)\s+|\s+(?:$|\n))/g,"").replace(/\s+/g,"")};String.prototype.noEsNum=function(){return!/^\d+$/.test(this)||isNaN(this)?!0:!1};
function asociarEventos(a){for(contador=0;contador<document.forms[0].length;contador++)if("text"==document.forms[0].elements[contador].type){document.forms[0].elements[contador].focus();break}switch(a){case "home":document.getElementById("iban-home").addEventListener("click",function(){cargarFormulario("iban")},!1);document.getElementById("ccc-home").addEventListener("click",function(){cargarFormulario("ccc")},!1);document.getElementById("ntc-home").addEventListener("click",function(){cargarFormulario("ntc")},
!1);document.getElementById("nif-home").addEventListener("click",function(){cargarFormulario("nif")},!1);document.getElementById("dni-home").addEventListener("click",function(){cargarFormulario("dni")},!1);document.getElementById("nie-home").addEventListener("click",function(){cargarFormulario("nie")},!1);document.getElementById("naf-home").addEventListener("click",function(){cargarFormulario("naf")},!1);document.getElementById("cccss-home").addEventListener("click",function(){cargarFormulario("cccss")},
!1);break;case "iban":urlEntidad="";document.forms[a].elements[0].addEventListener("keydown",function(){permitirSolo(event,"letra")},!1);document.forms[a].elements[0].addEventListener("keyup",function(){capitalizar(this);tabular(event,0);borrarAlerta(event)},!1);document.forms[a].elements[1].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[1].addEventListener("keyup",function(){tabular(event,1);borrarAlerta(event)},!1);document.forms[a].elements[2].addEventListener("keydown",
function(){permitirSolo(event,"numLetra")},!1);document.forms[a].elements[2].addEventListener("keyup",function(){capitalizar(this);borrarAlerta(event)},!1);break;case "ccc":urlEntidad="";document.forms[a].elements[0].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[0].addEventListener("keyup",function(){capitalizar(this);tabular(event,0);borrarAlerta(event)},!1);document.forms[a].elements[1].addEventListener("keydown",function(){permitirSolo(event,"num")},
!1);document.forms[a].elements[1].addEventListener("keyup",function(){tabular(event,1);borrarAlerta(event)},!1);document.forms[a].elements[2].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[2].addEventListener("keyup",function(){tabular(event,2);borrarAlerta(event)},!1);document.forms[a].elements[3].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[3].addEventListener("keyup",function(){borrarAlerta(event)},
!1);break;case "ntc":case "naf":case "cccss":document.forms[a].elements[0].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[0].addEventListener("keyup",function(){borrarAlerta(event)},!1);break;case "dni":document.forms[a].elements[1].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[1].addEventListener("keyup",function(){tabular(event,1);borrarAlerta(event)},!1);document.forms[a].elements[2].addEventListener("keydown",
function(){permitirSolo(event,"letra")},!1);document.forms[a].elements[2].addEventListener("keyup",function(){capitalizar(this);borrarAlerta(event)},!1);break;case "nie":document.forms[a].elements[0].addEventListener("change",function(){cambiarPropiedadesNIE()},!1);document.forms[a].elements[1].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[1].addEventListener("keyup",function(){tabular(event,1);borrarAlerta(event)},!1);document.forms[a].elements[2].addEventListener("keydown",
function(){permitirSolo(event,"letra")},!1);document.forms[a].elements[2].addEventListener("keyup",function(){capitalizar(this);borrarAlerta(event)},!1);break;case "nif":document.forms[a].elements[0].addEventListener("change",function(){cambiarPropiedadesNIF()},!1);document.forms[a].elements[1].addEventListener("keydown",function(){permitirSolo(event,"num")},!1);document.forms[a].elements[1].addEventListener("keyup",function(){tabular(event,1);borrarAlerta(event)},!1);document.forms[a].elements[2].addEventListener("keydown",
function(){permitirSolo(event,"numLetra")},!1);document.forms[a].elements[2].addEventListener("keyup",function(){capitalizar(this);borrarAlerta(event)},!1);break;case "about":propiedadesEquipo.visorPDF=detectarComplementoVisorPDF()?detectarComplementoVisorPDF():" ... ";a=0===comprobarCapacidadPDF()?"<span class='texto-capital'>"+propiedadesEquipo.visorPDF+"</span>":"<span class='texto-capital'>"+propiedadesEquipo.visorPDF+"</span><div style='width:90%;margin-top:6px;font-size:x-small;text-align:justify' class='texto-falsa-negrita'>Para visualizar el contenido de los archivos PDF desde cualquier aplicaci\u00f3n AIR, necesitas tener previamente instalado el -genuino- reproductor est\u00e1ndar Adobe READER (versi\u00f3n 8.1 \u00f3 superior). Que puedes obtener gratis desde la p\u00e1gina oficial: <a id='about-reader' href='#' class='enlaceTexto'>https://get.adobe.com/es/reader/</a></div>";
document.getElementById("about-versiones").innerHTML=propiedadesPrograma.versiones.tipo;document.getElementById("about-tirada").innerHTML=propiedadesPrograma.tirada;document.getElementById("about-id").innerHTML=propiedadesPrograma.identificador;document.getElementById("about-base-datos").innerHTML=propiedadesPrograma.baseDatosFecha;document.getElementById("registro-BE").addEventListener("click",function(){abrirEnNavegador("http://www.bde.es/bde/es/secciones/servicios/Particulares_y_e/Registros_de_Ent/")},
!1);document.getElementById("about-so").innerHTML=propiedadesEquipo.sistemaOperativoNombreComercial;document.getElementById("about-so-interno").innerHTML=propiedadesEquipo.sistemaOperativoNombreInterno;document.getElementById("about-idioma").innerHTML=propiedadesEquipo.idioma;document.getElementById("about-pantalla").innerHTML=propiedadesEquipo.pantalla;document.getElementsByClassName("about-runtime")[0].innerHTML=propiedadesEquipo.motorAIR;document.getElementsByClassName("about-runtime")[1].innerHTML=
propiedadesEquipo.motorAIRcomercial;document.getElementById("about-flash").innerHTML=propiedadesEquipo.flashPlayer;document.getElementById("about-webkit").innerHTML=propiedadesEquipo.webkit;document.getElementById("about-visor-pdf").innerHTML=a;document.getElementById("about-enlace-doc").addEventListener("click",function(){abrirArchivoConProgramaDeterminado()},!1);document.getElementById("about-enlace-github").addEventListener("click",function(){abrirEnNavegador("https://github.com/fooghub/Cdocs-HTML-Javascript-AIR")},
!1);document.getElementById("about-enlace-visor-fuente").addEventListener("click",function(){verRecursos()},!1);document.getElementById("about-enlace-licencia").addEventListener("click",function(){abrirNuevaVentanaNativa("html/LICENSE/license.html",null,"applicationDirectory","utilidad")},!1);document.getElementById("about-enlace-licencia-air").addEventListener("click",function(){abrirNuevaVentanaNativa("html/print/containerPDF.html","app:/pdf/air_sdk_license.pdf","applicationDirectory","normal")},
!1);document.getElementById("about-enlace-web").addEventListener("click",function(){abrirEnNavegador("http://www.foog.es/")},!1);document.getElementById("about-reader")&&document.getElementById("about-reader").addEventListener("click",function(){abrirEnNavegador("https://get.adobe.com/es/reader/")},!1);break;case "update":document.getElementById("update-so").innerHTML=propiedadesEquipo.sistemaOperativoNombreComercial;document.getElementById("update-runtime").innerHTML=propiedadesEquipo.motorAIR;document.getElementById("update-versiones-instalada").innerHTML=
propiedadesPrograma.versiones.larga;document.getElementById("update-versiones-actualizaciones").innerHTML=propiedadesPrograma.versiones.actualizaciones;document.getElementById("update-mensaje").innerHTML=propiedadesPrograma.versiones.actualizacionesMensaje;document.getElementById("alerta-update").innerHTML=propiedadesPrograma.versiones.actualizacionesError;break;case "download":document.getElementById("download-so").innerHTML=propiedadesEquipo.sistemaOperativoNombreComercial,document.getElementById("download-runtime").innerHTML=
propiedadesEquipo.motorAIR,document.getElementById("download-versiones-instalada").innerHTML=propiedadesPrograma.versiones.larga,document.getElementById("download-versiones-actualizaciones").innerHTML=propiedadesPrograma.versiones.actualizaciones,descargarActualizaciones()}}
function cambiarEstadoBotones(a){a=a||"inicial";var b=-1===["home","about","update","download"].indexOf(formularioActivo,0)?!1:!0,c=[2,2,2,2,2],d="";switch(a){case "inicial":formularioActivo?""===formularioActivo?(c=[1,1,-1,-1,1],d="SALIR"):"home"===formularioActivo?(c=[1,-1,-1,-1,1],d="INFORMACI\u00d3N"):"about"===formularioActivo?(c=[1,1,-1,-1,1],d="ACTUALIZAR",b=!0):"update"===formularioActivo?(d=propiedadesPrograma.versiones.actualizacionesDisponibles?"DESCARGAR":"CANCELAR",c=[1,-1,-1,-1,1]):
"download"===formularioActivo?(d="CANCELAR",c=[-1,-1,-1,-1,1]):(c=[1,1,0,0,1],d="VALIDAR"):(c=[1,1,-1,-1,1],d="SALIR");break;case "procesando":c=[0,0,0,0,0];break;case "acierto":c=[1,1,1,1,0];break;case "error":c=[1,1,1,0,0];break;case "mnu-activo":c=[1,2,2,2,2];break;case "mnu-inactivo":c=[0,2,2,2,2];break;case "descarga-cancelada":c=[1,-1,-1,-1,1],d="INICIO"}for(contador=0;contador<botones.length;contador++)switch(c[contador]){case -1:document.getElementById(botones[contador]).className="";document.getElementById(botones[contador]).className=
"botones-oculto";break;case 0:b?"botones-oculto"!==document.getElementById(botones[contador]).className&&(document.getElementById(botones[contador]).className="",document.getElementById(botones[contador]).className="botones-inactivo"):(document.getElementById(botones[contador]).className="",document.getElementById(botones[contador]).className="botones-inactivo");break;case 1:document.getElementById(botones[contador]).className="",document.getElementById(botones[contador]).className="botones-activo"}""!==
d&&(document.getElementById(botones[4]).innerHTML=d)}function capturarPulsacionesTeclado(a){a.stopPropagation();a.altKey||13!==a.keyCode?a.altKey&&80===a.keyCode&&(a=document.getElementById("botones-imprimir"),"botones-activo"===a.className&&/rimir$/i.test(a.innerHTML)&&formularioActivo&&imprimirFormulario(formularioActivo)):(a=document.getElementById("botones-validar"),"botones-activo"===a.className&&"VALIDAR"===a.innerHTML&&formularioActivo&&validarFormulario(formularioActivo))}
function validarFormulario(){if("botones-inactivo"!==document.getElementById("botones-validar").className&&"botones-oculto"!==document.getElementById("botones-validar").className)if(""===formularioActivo&&"SALIR"===document.getElementById("botones-validar").innerHTML)salir();else if("INFORMACI\u00d3N"===document.getElementById("botones-validar").innerHTML)cargarFormulario("about");else if("INICIO"===document.getElementById("botones-validar").innerHTML)cargarFormulario("home");else if("ACTUALIZAR"===
document.getElementById("botones-validar").innerHTML)comprobarActualizaciones();else if("DESCARGAR"===document.getElementById("botones-validar").innerHTML)cargarFormulario("download");else if("CANCELAR"===document.getElementById("botones-validar").innerHTML)"update"===formularioActivo&&cargarFormulario("home"),"download"===formularioActivo&&("descarga"===actualizacionesTarea?cancelarDescargaActualizaciones():(eliminarArchivosResiduales("update"),cargarFormulario("home")));else{for(contador=0;contador<
document.forms[formularioActivo].length;contador++)if("text"===document.forms[formularioActivo].elements[contador].type&&""===document.forms[formularioActivo].elements[contador].value){document.forms[formularioActivo].elements[contador].focus();return}for(contador=0;contador<document.forms[formularioActivo].length;contador++)"text"===document.forms[formularioActivo].elements[contador].type&&(document.forms[formularioActivo].elements[contador].value=document.forms[formularioActivo].elements[contador].value.eliminarEspaciosEnBlanco());
cambiarEstadoBotones("procesando");switch(formularioActivo){case "iban":verificarIBAN(document.forms[0].elements[0].value,document.forms[0].elements[1].value,document.forms[0].elements[2].value);break;case "ccc":document.forms.ccc.elements[0].value=rellenarConCeros(document.forms.ccc.elements[0].value,4);document.forms.ccc.elements[1].value=rellenarConCeros(document.forms.ccc.elements[1].value,4);document.forms.ccc.elements[2].value=rellenarConCeros(document.forms.ccc.elements[2].value,2);document.forms.ccc.elements[3].value=
rellenarConCeros(document.forms.ccc.elements[3].value,10);verificarCCC(document.forms.ccc.elements[0].value,document.forms.ccc.elements[1].value,document.forms.ccc.elements[2].value,document.forms.ccc.elements[3].value);break;case "ntc":verificarNTC(document.forms.ntc.elements[0].value);break;case "dni":document.forms.dni.elements[1].value=rellenarConCeros(document.forms.dni.elements[1].value,8);verificarDNI_NIE("dni",document.forms.dni.elements[1].value+document.forms.dni.elements[2].value);break;
case "nie":document.forms.nie.elements[1].value=rellenarConCeros(document.forms.nie.elements[1].value,7);verificarDNI_NIE("nie",document.forms.nie.elements[0].value+document.forms.nie.elements[1].value+document.forms.nie.elements[2].value);break;case "nif":document.forms.nif.elements[1].value=rellenarConCeros(document.forms.nif.elements[1].value,document.getElementById("valor-nif").maxLength);verificarNIF(document.forms.nif.elements[0].value+document.forms[0].elements[1].value+document.forms.nif.elements[2].value);
break;case "naf":verificarNAF_CCCSS("naf",document.forms.naf.elements[0].value);break;case "cccss":verificarNAF_CCCSS("cccss",document.forms.cccss.elements[0].value)}}}
function anunciarError(a,b,c){c=c||null;document.getElementById("imagen-estado").src="images/icono_2.png";document.getElementById("alerta-"+a).innerHTML=b;switch(a){case "iban":1===c?document.forms.iban.elements[0].focus():2===c?document.forms.iban.elements[1].focus():3===c?document.forms.iban.elements[2].focus():4===c?seleccionarTexto(document.forms.iban.elements[2],0,document.forms.iban.elements[2].value.length):5===c?seleccionarTexto(document.forms.iban.elements[0],0,2):6===c?seleccionarTexto(document.forms.iban.elements[1],
0,2):document.forms.iban.elements[2].focus();break;case "ntc":case "naf":case "cccss":b="ntc"===a?1:2;document.forms[a].elements[0].value.length<("cccss"===a?11:12)?document.forms[a].elements[0].focus():seleccionarTexto(document.forms[a].elements[0],document.forms[a].elements[0].value.length-b,document.forms[a].elements[0].value.length);break;case "dni":case "nie":case "nif":seleccionarTexto(document.forms[a].elements[2],0,1);break;case "ccc":seleccionarTexto(document.forms.ccc.elements[2],0,2)}cambiarEstadoBotones("error")}
function seleccionarTexto(a,b,c){"selectionStart"in a&&(a.selectionStart=b,a.selectionEnd=c,a.focus())}
function mostrarAcierto(a,b){document.getElementById("imagen-estado").src="images/icono_1.png";var c=document.getElementById("salida-"+a);c.innerHTML+=b;for(contador=0;contador<document.forms[a].length;contador++)"text"===document.forms[a].elements[contador].type?document.forms[a].elements[contador].readOnly=!0:"select-one"===document.forms[a].elements[contador].type?document.forms[a].elements[contador].disabled=!0:"hidden"===document.forms[a].elements[contador].type&&(document.forms[a].elements[contador].value=
formularioValorOculto),1<document.forms[a].elements[contador].value.length&&(document.forms[a].elements[contador].style.textAlign="center");document.getElementById("verificado-"+a).style.visibility="visible";"iban"!==a&&"ccc"!==a||""===urlEntidad||document.getElementById("enlaceEntidad-"+a)&&document.getElementById("enlaceEntidad-"+a).addEventListener("click",function(){abrirEnNavegador(urlEntidad)},!1);document.getElementById("alerta-"+a).innerHTML=plantillaAlertaInfo;cambiarEstadoBotones("acierto")}
function restaurarFormulario(){if("botones-inactivo"!==document.getElementById("botones-nuevo").className&&"botones-oculto"!==document.getElementById("botones-nuevo").className&&""!==formularioActivo){var a=formularioActivo;for(contador=0;contador<document.forms[a].length;contador++)"text"===document.forms[a].elements[contador].type?(document.forms[a].elements[contador].readOnly=!1,1<document.forms[a].elements[contador].getAttribute("maxlength")&&(document.forms[a].elements[contador].style.textAlign=
"left"),document.forms[a].elements[contador].value=""):"select-one"===document.forms[a].elements[contador].type?document.forms[a].elements[contador].disabled=!1:"hidden"===document.forms[a].elements[contador].type&&(document.forms[a].elements[contador].value="");document.getElementById("verificado-"+a).style.visibility="hidden";document.getElementById("imagen-estado").src="images/icono_0.png";urlEntidad="";1<document.getElementById("salida-"+a).parentNode.length&&document.getElementById("salida-"+
a).removeChild(document.getElementById("salida-"+a).lastChild);"nif"===a&&(document.getElementById("texto-informativo-nif").innerHTML="SIETE N\u00daMEROS",document.getElementById("valor-nif").maxLength="7",document.getElementById("letra-nif").placeholder="(N/L)");for(contador=0;contador<document.forms[0].length;contador++)if("text"===document.forms[a].elements[contador].type&&""===document.forms[a].elements[contador].value){document.forms[a].elements[contador].focus();break}borrarAlertaVoluntario(a);
document.getElementById(a).reset();cambiarEstadoBotones("inicial")}}
function permitirSolo(a,b){var c=a.keyCode;for(contador=0;contador<=teclasRestringidas.length;contador++)if(c===teclasRestringidas[contador])return;switch(b){case "num":if(a.altKey||a.ctrlKey||a.shiftKey)a.returnValue=!1;if(48>c)a.returnValue=!1;else if(48<=c&&57>=c)break;else if(57<c&&96>c)a.returnValue=!1;else if(96<=c&&105>=c)break;else a.returnValue=!1;break;case "letra":if(a.altKey||a.ctrlKey)a.returnValue=!1;if(65>c||90<c)a.returnValue=!1;else break;break;case "numLetra":if(a.altKey||a.ctrlKey)a.returnValue=
!1;a.shiftKey&&57>=c&&48<=c&&(a.returnValue=!1);48>c?a.returnValue=!1:48<=c&&57>=c||(57<c&&65>c?a.returnValue=!1:65<=c&&90>=c||(90<c&&96>c?a.returnValue=!1:96<=c&&105>=c||(a.returnValue=!1)))}}function capitalizar(a){a.value=a.value.toString().toUpperCase()}function rellenarConCeros(a,b){var c="";a=a.toString();if(a.length<parseInt(b,10))for(var d=b;d>a.length;d--)c+="0";return c.concat(a)}
function tabular(a,b){var c=a.keyCode;for(contador=0;contador<=teclasRestringidas.length;contador++)if(c==teclasRestringidas[contador])return;var c=document.forms[0].elements[b].getAttribute("maxlength"),d=document.forms[0].elements[b].value.length;d==c&&(b=++b,c=document.forms[0].elements[b].getAttribute("maxlength"),d=document.forms[0].elements[b].value.length,d!=c&&document.forms[0].elements[b].focus())}
function borrarAlerta(a){if(13!=a.keyCode&&!0===errorValidar){var b;clearTimeout(b);b=setTimeout(function(){document.getElementById("alerta-"+formularioActivo).innerHTML="&#160;";errorValidar=!1;document.getElementById("imagen-estado").src="images/icono_0.png";cambiarEstadoBotones("inicial")},10)}}
function borrarAlertaVoluntario(a){document.getElementById("alerta-"+a).innerHTML="&#160;";errorValidar=!1;document.getElementById("imagen-estado").src="images/icono_0.png";cambiarEstadoBotones("inicial")}function lanzarEvento(a,b){var c=document.createEvent("HTMLEvents");c.initEvent(b,!0,!0);return!a.dispatchEvent(c)}
function notificarConHumanJS(a,b,c){switch(arguments.length){case 1:b="normal";c=2500;break;case 2:c="normal"==b?2500:5E3}humane.log(a,{timeout:c,clickToClose:!0,addnCls:"normal"==b?"humane-original":"humane-original-error"},function(){cambiarEstadoBotones("mnu-activo")})}
function cargarFormulario(a){if("portada"===a){if("botones-inactivo"===document.getElementById("botones-inicio").className||"botones-oculto"===document.getElementById("botones-inicio").className)return;a="home"}document.getElementById("imagen-estado").src="images/icono_0.png";formularioActivo="";errorAJAX=!1;formularioValorOculto="";var b="ninguno",c=formularios.indexOf(a,0);desactivarElementoMnu(c);var d=new XMLHttpRequest;d.onreadystatechange=function(){4===d.readyState&&200==d.status&&(document.getElementById("contenido").innerHTML=
d.responseText,formularioActivo=a,cambiarTitularVentanaNativa(a),asociarEventos(a),cambiarEstadoBotones("inicial"),errorAJAX=!1,"about"===a?document.getElementById("pie").style.visibility="visible":document.getElementById("pie").style.visibility="hidden")};d.open("GET","html/forms/"+a+".html",!1);try{d.send(null)}catch(e){b=e}finally{document.getElementById("pie-anualidad-corriente").innerHTML=fechaSistema.aaaa,protector.activo&&protector.cerrar(),"ninguno"!==b&&(errorAJAX=!0,b="<div class='errorAJAX'><img src='images/alerta_128.png' alt='' title='' /><div>\u00a1\u00a1ATENCI\u00d3N!!</div><p>"+
b+"</p><p>Recurso - app:/html/forms/"+a+".html</p></div>",d.abort(),document.getElementById("contenido").innerHTML=b,cambiarTitularVentanaNativa(a),cambiarEstadoBotones("inicial"),document.getElementById("pie").style.visibility="hidden")}}
function obtenerFecha(a){a=a||null;var b,c;null!==a?isNaN(a)?(/^\d{1,2}[./-]\d{1,2}[./-]\d{4,}$/.test(a)?(a=a.replace(/\/|\./g,"-"),a=a.split("-").reverse().join("-")):/^\d{4,}[./-]\d{1,2}[./-]\d{1,2}$/.test(a)?a=a.replace(/\/|\./g,"-"):notificarConHumanJS("ERROR FECHA:<BR />Wrong date format","error"),b=a.split("-")[2],c=a.split("-")[1],a=a.split("-")[0],1E3>a&&(a=1E3),9999<a&&(a=9999),1>c&&(c=1),12<c&&(c=12),1>b&&(b=1),b>(new Date(a,c,0)).getDate()&&(b=(new Date(a,c,0)).getDate()),(1>b||31<b||1>
c||12<c)&&notificarConHumanJS("ERROR FECHA:<BR />Wrong date format","error"),(1E3>a||9999<a)&&notificarConHumanJS("ERROR FECHA:<BR />Date out of ranget","error"),b=new Date(a,c-1,b)):-306102276E5>parseInt(a,10)||2534022108E5<parseInt(a,10)?notificarConHumanJS("ERROR FECHA:<BR />Date out of ranget","error"):b=new Date(parseInt(a,10)):b=new Date;this.d=b.getDate();this.dd=10>this.d?"0"+this.d:this.d;this.nDs=b.getDay();this.dsemana="domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" ")[this.nDs];
this.wd="sunday monday tuesday wednesday thursday friday saturday".split(" ")[this.nDs];this.m=b.getMonth()+1;this.mm=10>this.m?"0"+this.m:this.m;this.mes="enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" ")[b.getMonth()];this.mo="january february march april may june july august september october november december".split(" ")[b.getMonth()];this.aaaa=b.getFullYear();this.bisiesto=29===(new Date(this.aaaa,2,0)).getDate()?!0:!1;this.horas=10>b.getHours()?
"0"+b.getHours():b.getHours();this.minutos=10>b.getMinutes()?"0"+b.getMinutes():b.getMinutes();this.segundos=10>b.getSeconds()?"0"+b.getSeconds():b.getSeconds();this.uDm=(new Date(this.aaaa,this.m,0)).getDate();this.pDm=(new Date(this.aaaa,this.m-1,1)).getDay();this.marcaTemporal=Date.parse(b)}
function detectarComplementoVisorPDF(){var a=navigator.mimeTypes&&navigator.mimeTypes["application/pdf"],b=[];"undefined"!==typeof a&&a.enabledPlugin&&(a.enabledPlugin.name&&(b[0]=a.enabledPlugin.name),a.enabledPlugin.version?b[1]=a.enabledPlugin.version:a.enabledPlugin.description&&/\d/g.test(a.enabledPlugin.description)&&(b[1]=a.enabledPlugin.description.replace(/[^\d\.]/g,"")));return b=0===b.length?!1:2===b.length?b[0]+" "+b[1]:b[0]}
function cambiarPropiedadesNIF(){"I"===document.getElementById("selector-nif").value?(document.getElementById("texto-informativo-nif").innerHTML="OCHO N\u00daMEROS",document.getElementById("valor-nif").maxLength="8",document.getElementById("letra-nif").placeholder="LETRA"):(document.getElementById("texto-informativo-nif").innerHTML="SIETE N\u00daMEROS",document.getElementById("valor-nif").maxLength="7",document.getElementById("letra-nif").placeholder="(N/L)");""!==document.getElementById("valor-nif").value&&
(document.getElementById("valor-nif").value="");""!==document.getElementById("letra-nif").value&&(document.getElementById("letra-nif").value="");document.getElementById("valor-nif").focus();borrarAlertaVoluntario("nif")}
function cambiarPropiedadesNIE(){""!==document.getElementById("valor-nie").value&&(document.getElementById("valor-nie").value="");""!==document.getElementById("letra-nie").value&&(document.getElementById("letra-nie").value="");document.getElementById("valor-nie").focus();borrarAlertaVoluntario("nie")}
function verificarIBAN(a,b,c){var d=a+b+c,e=!1,f="",h,g=!1,k;b="";if(2>document.forms.iban.elements[0].value.length)errorValidar=!0,anunciarError("iban","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El c\u00f3digo (ISO) del pa\u00eds est\u00e1 formado por DOS caracteres alfab\u00e9ticos.</span></span>",1);else if(2>document.forms.iban.elements[1].value.length)errorValidar=!0,anunciarError("iban","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>En el IBAN los d\u00edgitos de control (DC) son DOS n\u00fameros.</span></span>",
2);else if("ES"===document.forms.iban.elements[0].value&&20!==document.forms.iban.elements[2].value.length)errorValidar=!0,anunciarError("iban","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El C\u00f3digo de cuenta (en Espa\u00f1a) est\u00e1 formado por VEINTE n\u00fameros.</span></span>",3);else if("ES"===document.forms.iban.elements[0].value&&isNaN(document.forms.iban.elements[2].value))errorValidar=!0,anunciarError("iban",
"<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El C\u00f3digo de cuenta (en Espa\u00f1a) s\u00f3lo admite N\u00daMEROS. Gracias.</span></span>",4);else try{e=IBAN.isValid(d),h=IBAN.toBBAN(d," "),g=IBAN.isValidBBAN(a,h),k=IBAN.printFormat(d," ")}catch(l){f=l}finally{""!==f?/No country with code/.test(f)?(errorValidar=!0,anunciarError("iban","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>La aplicaci\u00f3n no registra ning\u00fan pa\u00eds con el c\u00f3digo: &#8220;<span class='alerta-texto-error-dc'>"+
a+"</span>&#8221;.</span>",5)):/^TypeError: Result of expression \'this\.\_regex\(\)\.exec\(iban.slice\(4\)\)\' \[null\] is not an object\.$/.test(f)||/Invalid BBAN/.test(f)?(errorValidar=!0,anunciarError("iban","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>Formato de C\u00f3digo de Cuenta inadecuado para pa\u00eds con c\u00f3digo: &#8220;"+a+"&#8221.</span></span>",4)):(errorValidar=!0,anunciarError("iban","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+
f+".</span></span>")):e?("ES"!==a?(c=obtenerPaises(a)&&"DESCONOCIDO"!==obtenerPaises(a)?obtenerPaises(a):"DESCONOCIDO",b="<div class='formulario-salida-resultados'><hr class='separador' /><div>C\u00f3digo de Cuenta : "+h+"</div><div style='margin-top:6px;'>Pa\u00eds: "+a+" &#8212; "+c+".</div></div>",formularioValorOculto=k+"|"+h+"|"+c):(a=buscarEntidadBancaria(c.substr(0,4)))?"DESCONOCIDA"===a?(formularioValorOculto=k+"|"+h+"|DESCONOCIDA",b="<div class='formulario-salida-resultados'><hr class='separador' /><div>Entidad: DESCONOCIDA</div></div>"):
(a=a.split("|"),formularioValorOculto=k+"|"+h+"|"+a[5]+" (Espa\u00f1a)|"+a[3]+"|"+a[4],""===a[3]?(urlEntidad="http://app.bde.es/ren/app/Search?CFG=ConsultaDetalleEntidadCon.xml&TipoFormato=XSL&Paginate=OPEN&CODBE="+a[0]+"&DONDE=11&RADIO=0&VDETALLE=S",b="<div class='formulario-salida-resultados'><hr class='separador' /><div><a href='#' id='enlaceEntidad-iban' class='enlaceTexto'>"+a[5]+"</a></div></div>"):b="<div class='formulario-salida-resultados'><hr class='separador' /><div>"+a[5]+"</div></div>"):
(formularioValorOculto=k+"|"+h+"|DESCONOCIDA",b="<div class='formulario-salida-resultados'><hr class='separador' /><div>Entidad: DESCONOCIDA</div></div>"),mostrarAcierto("iban",b)):(b="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>IBAN err\u00f3neo. Por favor, revisa TODOS los datos introducidos.</span></span>",errorValidar=!0,g?anunciarError("iban",b,6):anunciarError("iban",b,4))}}
function verificarCCC(a,b,c,d){var e="",f="",e=f=f="",h=0,g=0,e="00"+a+b+d,f=c;c=[1,2,4,8,5,10,9,7,3,6];for(var k=0;k<e.length;k++)10>k&&(h+=parseInt(e.charAt(k),10)*c[k]),10<=k&&(g+=parseInt(e.charAt(k),10)*c[k-10]);c=10<=11-h%11?(11-(11-h%11)).toString():(11-h%11).toString();g=10<=11-g%11?(11-(11-g%11)).toString():(11-g%11).toString();f===c+g?(f=parseInt(a+b,10)%97,f=f.toString()+c+g+b.substring(0,2),f=parseInt(f,10)%97,f=f.toString()+d.substring(2,e.length)+"142800",f=parseInt(f,10)%97,e=10>98-
f?"0"+(98-f):(98-f).toString(),f="ES"+e+a+b+c+g+d,e="ES"+e+"|",(a=buscarEntidadBancaria(a))?"DESCONOCIDA"===a?(e+="DESCONOCIDA",f="<div class='formulario-salida-resultados'><div>Entidad: DESCONOCIDA</div><div style='margin-top:12px;'>IBAN: "+f+"</div></div>"):(a=a.split("|"),""===a[3]?(e+=a[1],urlEntidad="http://app.bde.es/ren/app/Search?CFG=ConsultaDetalleEntidadCon.xml&TipoFormato=XSL&Paginate=OPEN&CODBE="+a[0]+"&DONDE=11&RADIO=0&VDETALLE=S",f="<div class='formulario-salida-resultados'><div><a href='#' id='enlaceEntidad-ccc' class='enlaceTexto'>"+
a[5]+"</a></div><div style='margin-top:12px;'>IBAN: "+f+"</div></div>"):(e=e+a[1]+"|"+a[3]+"|"+a[4],f="<div class='formulario-salida-resultados'><div>"+a[5]+"</div><div style='margin-top:12px;'>IBAN: "+f+"</div></div>")):f="<div class='formulario-salida-resultados'><div>Entidad: DESCONOCIDA</div><div style='margin-top:12px;'>IBAN: "+f+"</div></div>",formularioValorOculto=e,mostrarAcierto("ccc",f)):(errorValidar=!0,anunciarError("ccc","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El D\u00edgito de Control (DC) deber\u00eda ser igual a &#8220;<span class='alerta-texto-error-dc'>"+
(c+g)+"</span>&#8221.</span>"))}
function verificarNTC(a){var b="",c="",d="",c=b="",e=0,f;if(12<=a.length){for(var h=[],d=[],g=[[/^3[47]\d{13}$/,"American Express",""],[/^(?:62|88)\d{14,17}$/,"China UnionPay",""],[/^3(?:0[0-5]|[68][0-9])[0-9]{11}$/,"Diners Club",""],[/^3(?:0[0-5][0-9]{11}|[68][0-9]{12}$)/,"Diners Club","Carte Blanche"],[/^(?:2014|2149)\d{11}/,"Diners Club","enRoute"],[/^6(?:011\d{12}|5\d{14}|4[4-9]\d{13}|22(?:1(?:2[6-9]|[3-9]\d)|[2-8]\d{2}|9(?:[01]\d|2[0-5]))\d{10})$/,"Discover",""],[/^600833\d{10,13}$/,"El Corte Ingl\u00e9s",
""],[/^6(?:37|38|39)\d{13}$/,"InstantPayment",""],[/^(?:3[0-9]{15}|(2100|2131|1800)[0-9]{11})$/,"JCB",""],[/^6(?:304|706|709|771)\d{12,15}$/,"Laser",""],[/^5[1-5]\d{14}$/,"MasterCard"],[/(?:5018|5020|5038|6304|6759|676[123])\d{12,15}$/,"MasterCard - Maestro",""],[/((?:6334|6767)\d{12}(?:\d\d)?\d?)/,"MasterCard - Maestro","Solo"],[/(?:(?:(?:4903|4905|4911|4936|6333|6759)\d{12})|(?:(?:564182|633110)\d{10})(\d\d)?\d?)/,"MasterCard - Maestro","Switch"],[/^(4\d{12}(?:\d{3})?)$/,"VISA",""],[/^5019\d{12}/,
"Dankort","VISA"],[/^8699\d{11}/,"Voyager",""]],c=parseInt(a.charAt(a.length-1),10),b=0===a.length%2?a:"0"+a,k=0;k<b.length;k++)f=10>2*parseInt(b.charAt(k),10)?2*parseInt(b.charAt(k),10):2*parseInt(b.charAt(k),10)-9,k&1?h.unshift(parseInt(b.charAt(k),10)):h.unshift(f);h.forEach(function(a){e+=a});if(0===e%10){for(f=0;f<g.length;f++)g[f][0].test(a)&&(b=g[f][1],c=g[f][2],0===d.length?(b&&""!==b&&d.unshift(b),c&&""!==c&&d.unshift(c)):2>d.length&&(-1===d.indexOf(b)&&d.unshift(b),-1===d.indexOf(c)&&d.unshift(c)));
formularioValorOculto=d=0<d.length?d[1]&&""!==d[1]?d[0]+" / "+d[1]:d[0]:"DESCONOCIDA";mostrarAcierto("ntc","<div class='formulario-salida-resultados'><hr class='separador' /><div>TARJETA : "+d+"</div></div>")}else a=10===10-(e-c)%10?"0":(10-(e-c)%10).toString(),errorValidar=!0,anunciarError("ntc","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El D\u00edgito de Control deber\u00eda ser igual a &#8220;<span class='alerta-texto-error-dc'>"+
a+"</span>&#8221.</span>")}else errorValidar=!0,anunciarError("ntc","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>M\u00ednimo DOCE n\u00fameros. Gracias.</span>")}
function verificarDNI_NIE(a,b){var c="",d="",e=c="";"dni"==a?(c=b.substr(0,8),d=b.substr(8,1),c="TRWAGMYFPDXBNJZSQVHLCKE".substr(parseInt(c,10)%23,1)):(e=b.substr(0,1),c=b.substr(1,7),d=b.substr(8,1),c="TRWAGMYFPDXBNJZSQVHLCKE".substr(parseInt(("X"==e?"0":"Y"==e?"1":"2")+c,10)%23,1));d==c?mostrarAcierto(a,"dni"===a?"<div class='formulario-salida-resultados' style='font-size:12px;text-align:justify;'>El DNI es un documento p\u00fablico, personal e intransferible, emitido por el Ministerio del Interior, que acredita la identidad y los datos personales de su titular, as\u00ed como la nacionalidad espa\u00f1ola del mismo.</div>":
"X"===e?"<div class='formulario-salida-resultados'><hr class='separador' /><div style='font-size:12px;'>NIE asignado antes de julio de 2008.</div></div>":"<div class='formulario-salida-resultados'><hr class='separador' /><div style='font-size:12px;'>NIE asignado despu\u00e9s de julio de 2008.</div></div>"):(errorValidar=!0,anunciarError(a,"<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>La letra final (D\u00edgito de Control) deber\u00eda ser igual a &#8220;<span class='alerta-texto-error-dc'>"+
c+"</span>&#8221;.</span>"))}
function verificarNAF_CCCSS(a,b){var c="",d="",d=d="",c=0,e;"naf"===a&&12>b.length?(errorValidar=!0,anunciarError("naf","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>Introduce DOCE n\u00fameros. Gracias!</span>")):"cccss"===a&&11>b.length?(errorValidar=!0,anunciarError("cccss","<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>Introduce ONCE n\u00fameros. Gracias!</span>")):(e=
parseInt(b.substr(0,2),10),"naf"===a?(c=b.substr(2,8),d=b.substr(10,11)):(c=b.substr(2,7),d=b.substr(9,10)),c=1E7>parseInt(c,10)?1E7*e+parseInt(c,10):e+parseInt(c,10),c=10>c%97?"0"+c%97:(c%97).toString(),d===c?(formularioValorOculto=d=57<e?"DESCONOCIDA":obtenerProvincia(e),d="naf"===a?"<div class='formulario-salida-resultados'><hr class='separador' /><div>Provincia de afiliaci\u00f3n : "+d.toUpperCase()+"</div></div>":"<div class='formulario-salida-resultados'><hr class='separador' /><div>Provincia de actividad : "+
d.toUpperCase()+"</div></div>",mostrarAcierto(a,d)):(errorValidar=!0,anunciarError(a,"<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>La serie de n\u00fameros deber\u00eda terminar en &#8220;<span class='alerta-texto-error-dc'>"+c+"</span><span>&#8221; (DC).</span></span>")))}
function verificarNIF(a){var b="",c="",d="",e="DESCONOCIDA",f="",f=!1,h=c=0,g,k=["X","Y","Z"],b=a.substr(0,1),d=a.substr(1,a.length-2),l=d.substr(0,2);a=a.substr(a.length-1,1);if(/^[XYZI]$/.test(b)){f=!0;if("I"!==b)for(g in c=b,k)b===k[g]&&(b=g.toString());else c="DNI",b="";d="TRWAGMYFPDXBNJZSQVHLCKE".charAt(parseInt(b+d,10)%23);d=a===d?"ACIERTO":"<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>La letra final deber\u00eda ser igual a &#8220;<span class='alerta-texto-error-dc'>"+
d+"</span><span>&#8221;.</span></span>"}else{for(g=0;g<d.length;g++)0===g%2?c+=9<2*parseInt(d.charAt(g),10)?2*parseInt(d.charAt(g),10)-9:2*parseInt(d.charAt(g),10):h+=parseInt(d.charAt(g),10);g=9<c+h?10-(c+h)%10:10-(c+h);g=10===g?0:g;d="JABCDEFGHI".charAt(g);/^[ABEHU]$/.test(b)?(c=b,d=a===g.toString()?"ACIERTO":"<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El car\u00e1cter final (de control) deber\u00eda ser el n\u00famero &#8220;<span class='alerta-texto-error-dc'>"+
g+"</span><span>&#8221;.</span></span>"):/^[KLMPQRS]$/.test(b)?(/^[KLM]$/.test(b)&&(f=!0),c=b,d=a===d?"ACIERTO":"<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El car\u00e1cter final (de control) deber\u00eda ser la letra &#8220;<span class='alerta-texto-error-dc'>"+d+"</span><span>&#8221;.</span></span>"):(c=b,d=a===g.toString()||a===d?"ACIERTO":"<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>El car\u00e1cter final (de control) deber\u00eda ser el n\u00famero &#8220;<span class='alerta-texto-error-dc'>"+
g+"</span><span>&#8221; \u00f3 la letra &#8220;</span><span class='alerta-texto-error-dc'>"+d+"&#8221;.</span>")}"ACIERTO"===d?(!1===f&&(e=obtenerProvincia(l)&&"DESCONOCIDA"!==obtenerProvincia(l)?obtenerProvincia(l):"DESCONOCIDA"),f="<span>Tipo &#8220;<span class='texto-capital'>"+c+"</span>&#8221; : </span>","DNI"===c&&(c="I"),d="DESCONOCIDA"===e?"<div class='formulario-salida-resultados-nif'><div>"+f+buscarTipoNIF(c)+"</div></div>":"<div class='formulario-salida-resultados-nif'><div>"+f+buscarTipoNIF(b)+
"</div><div>Con sede (si el NIF fue asignado antes de 2009) en la provincia de "+e.toUpperCase()+".</div></div>",formularioValorOculto=buscarTipoNIF(c)+"|"+e,mostrarAcierto("nif",d)):(errorValidar=!0,anunciarError("nif",d))}
function obtenerNombreComercialSO(){var a=propiedadesEquipo.sistemaOperativo,b={"1.0":"Hera","10.0":"Cheetah","10.1":"Puma","10.2":"Jaguar","10.3":"Panther","10.4":"Tiger","10.5":"Leopard","10.6":"Snow Leopard","10.7":"Lion","10.8":"Mountain Lion","10.9":"Mavericks","10.10":"Yosemite","10.11":"El Capitan"};switch(propiedadesEquipo.sistemaOperativoAlias){case "mac":vesionesNumeral=a.match(/\d+\.\d+/i)[0];b.hasOwnProperty(vesionesNumeral)?propiedadesEquipo.sistemaOperativoNombreComercial="OS X "+b[vesionesNumeral]:
propiedadesEquipo.sistemaOperativoNombreComercial=a;break;case "lnx":propiedadesEquipo.sistemaOperativoNombreComercial="Linux";break;case "and":propiedadesEquipo.sistemaOperativoNombreComercial="Android";break;case "iph":propiedadesEquipo.sistemaOperativoNombreComercial="iPhone";break;default:propiedadesEquipo.sistemaOperativoNombreComercial=a}propiedadesEquipo.sistemaOperativoNombreComercial!==a&&(propiedadesEquipo.sistemaOperativoNombreInterno=a)}
function cambiarTitularVentanaNativa(a){switch(a){case "home":window.nativeWindow.title="CDOCS";break;case "cccss":window.nativeWindow.title="CDOCS : CCC (ss)";break;case "about":window.nativeWindow.title="CDOCS : ACERCA DE ...";break;case "update":window.nativeWindow.title="CDOCS : ACTUALIZACIONES";break;case "download":window.nativeWindow.title="CDOCS : ACTUALIZACIONES - DESCARGA";break;default:window.nativeWindow.title="CDOCS : "+a.toUpperCase()}errorAJAX&&(window.nativeWindow.title="CDOCS : ERROR")}
function comprobarCapacidadPDF(){var a=0;air.HTMLLoader.pdfCapability!==air.HTMLPDFCapability.STATUS_OK&&(a=air.HTMLLoader.pdfCapability===air.HTMLPDFCapability.ERROR_INSTALLED_READER_NOT_FOUND?3201:air.HTMLLoader.pdfCapability===air.HTMLPDFCapability.ERROR_INSTALLED_READER_TOO_OLD?3202:air.HTMLLoader.pdfCapability===air.HTMLPDFCapability.ERROR_PREFERRED_READER_TOO_OLD?3203:air.HTMLLoader.pdfCapability===air.HTMLPDFCapability.ERROR_CANNOT_LOAD_READER?3204:3205);return a}
function imprimirFormulario(){if("botones-inactivo"!==document.getElementById("botones-imprimir").className&&"botones-oculto"!==document.getElementById("botones-imprimir").className&&""!==formularioActivo){var a,b=formularioActivo;borrarAlertaVoluntario(b);document.getElementById("alerta-"+b).innerHTML=plantillaAlertaEspera;cambiarEstadoBotones("procesando");var c=comprobarCapacidadPDF();0!==c?(clearTimeout(a),borrarAlertaVoluntario(b),a=setTimeout(function(){abrirNuevaVentanaNativa("html/print/errorPDF.html",
c.toString()+"|","applicationDirectory","utilidad");borrarAlertaVoluntario(b);cambiarEstadoBotones("acierto")},500)):(clearTimeout(a),a=setTimeout(function(){crearArchivoPDF(b)},500))}}
function buscarEntidadBancaria(a){a=parseInt(a,10);a=a.toString();var b="DESCONOCIDA",c="";try{var d=new air.SQLConnection,e=air.File.applicationDirectory.resolvePath("db/entidades_financieras_ES.db"),e=d.open(e),f=new air.SQLStatement;f.sqlConnection=d;f.addEventListener(air.SQLEvent.RESULT,function(){var a=f.getResult();null!==a.data&&(b=a.data[0].COD_BE+"|"+a.data[0].NOMBRE_50+"|"+a.data[0].NOMBRE_105+"|"+a.data[0].FECHA_BAJA+"|"+a.data[0].MOTVO_BAJA+"|"+a.data[0].NOMBRE_35+"|"+a.data[0].ANAGRAMA);
d.close()});f.text='select * FROM entidades WHERE COD_BE="'+a+'"';f.execute()}catch(h){c=h}finally{""!==c&&notificarConHumanJS("\u00a1ATENCI\u00d3N!<BR />"+c,"error")}return b}
function construirMnuEmergente(){mnuEmergente=new air.NativeMenu;mnuEmergente.addEventListener(air.Event.SELECT,gestionarElementoSeleccionado);mnuEmergente.addItem(new air.NativeMenuItem("Inicio"));mnuEmergente.addItem(new air.NativeMenuItem("IBAN"));mnuEmergente.addItem(new air.NativeMenuItem("CCC"));mnuEmergente.addItem(new air.NativeMenuItem("NTC"));mnuEmergente.addItem(new air.NativeMenuItem("NIF"));mnuEmergente.addItem(new air.NativeMenuItem("DNI"));mnuEmergente.addItem(new air.NativeMenuItem("NIE"));
mnuEmergente.addItem(new air.NativeMenuItem("NAF"));mnuEmergente.addItem(new air.NativeMenuItem("CCC (SS)"));mnuEmergente.addItem(new air.NativeMenuItem("",!0));mnuEmergente.addItem(new air.NativeMenuItem("Actualizaciones"));mnuEmergente.addItem(new air.NativeMenuItem("Acerca de ..."));mnuEmergente.addItem(new air.NativeMenuItem("",!0));var a=mnuEmergente.addItem(new air.NativeMenuItem("Salir"));air.NativeWindow.supportsMenu?(a.keyEquivalent="f4",a.keyEquivalentModifiers=[air.Keyboard.ALTERNATE]):
air.NativeApplication.supportsMenu&&(a.keyEquivalent="s",a.keyEquivalentModifiers=[air.Keyboard.COMMAND],a.label="Salir");return mnuEmergente}
function gestionarElementoSeleccionado(a){a.preventDefault();var b="";switch(a.target.label){case "Inicio":b="home";break;case "IBAN":b="iban";break;case "CCC":b="ccc";break;case "NTC":b="ntc";break;case "NIF":b="nif";break;case "DNI":b="dni";break;case "NIE":b="nie";break;case "NAF":b="naf";break;case "CCC (SS)":b="cccss";break;case "Actualizaciones":b="actualizaciones";break;case "Acerca de ...":b="about";break;case "Salir":b="salir"}""!==b&&("salir"===b?salir():"actualizaciones"===b?comprobarActualizaciones():
cargarFormulario(b))}function visualizarMnuEmergente(a){a.preventDefault();"botones-inactivo"!==document.getElementById("botones-mnu").className&&(a="mac"===propiedadesEquipo.sistemaOperativoAlias?480:384,mnuY=30,mnuEmergente.display(window.nativeWindow.stage,a,mnuY))}
function desactivarElementoMnu(a){for(var b=0;b<mnuEmergente.items.length;b++)mnuEmergente.items[b].enabled||(mnuEmergente.items[b].enabled=!0),mnuEmergente.items[b].checked&&(mnuEmergente.items[b].checked=!1);-1<a&&(9<=a&&(a+=1),mnuEmergente.items[a].checked=!0,mnuEmergente.items[a].enabled=!1)}
function activarMnuIcono(){var a="ninguno",b;try{var c=function(a){air.NativeApplication.nativeApplication.icon.bitmaps=[a.target.content.bitmapData];iniciar()},d=new air.Loader,e=new air.NativeMenu,f=e.addItem(new air.NativeMenuItem("CDOCS "+propiedadesPrograma.versiones.larga));e.addItem(new air.NativeMenuItem("",!0));air.NativeApplication.supportsSystemTrayIcon&&e.addItem(new air.NativeMenuItem("Salir")).addEventListener(air.Event.SELECT,function(a){air.NativeApplication.nativeApplication.icon.bitmaps=
[];salir()});e.items[0].checked=!0;e.items[0].enabled=!1;f.addEventListener(air.Event.SELECT,function(a){window.nativeWindow.restore()});e.addEventListener("preparing",function(a){a.preventDefault();e.items[0].enabled=ventanaPrincipalMinimizada?!0:!1});air.NativeApplication.supportsSystemTrayIcon&&(b=new air.URLRequest("images/icono_bandeja.png"),d.contentLoaderInfo.addEventListener(air.Event.COMPLETE,c),d.load(b),air.NativeApplication.nativeApplication.icon.tooltip="CDOCS",air.NativeApplication.nativeApplication.icon.menu=
e,d.contentLoaderInfo.addEventListener(air.IOErrorEvent.IO_ERROR,function(a){iniciar()}));air.NativeApplication.supportsDockIcon&&(b=new air.URLRequest("images/icono_muelle.png"),d.contentLoaderInfo.addEventListener(air.Event.COMPLETE,c),d.load(b),air.NativeApplication.nativeApplication.icon.menu=e,d.contentLoaderInfo.addEventListener(air.IOErrorEvent.IO_ERROR,function(a){iniciar()}))}catch(h){a=h}finally{"ninguno"!==a&&iniciar()}}
function obtenerPropiedadesPrograma(){var a=air.NativeApplication.nativeApplication.applicationDescriptor,a=(new DOMParser).parseFromString(a,"text/xml");propiedadesPrograma.identificador=a.getElementsByTagName("id")[0].firstChild.nodeValue;propiedadesPrograma.versiones.larga=a.getElementsByTagName("versionNumber")[0].firstChild.nodeValue;var b=propiedadesPrograma.versiones.larga.split(".");propiedadesPrograma.versiones.corta=1<b.length?b[0]+"."+b[1]:b;propiedadesPrograma.versiones.tipo=a.getElementsByTagName("versionLabel")[0].firstChild.nodeValue}
function monitorizarInternet(){monitor=new air.URLMonitor(new air.URLRequest("http://www.google.com/"));monitor.addEventListener(air.StatusEvent.STATUS,function(){internetDisponible=monitor.available});monitor.start()}function abrirEnNavegador(a){internetDisponible?(a=new air.URLRequest(a),air.navigateToURL(a)):notificarConHumanJS("No fue posible conectarse a Internet","normal",5E3)}
function abrirArchivoConProgramaDeterminado(){protector.abrir();cambiarEstadoBotones("procesando");var a="ninguno",b,c=comprobarCapacidadPDF(),d=[3201,3202,3203,3204];try{var e=air.File.applicationDirectory.resolvePath("app:/pdf/documentation_010.pdf"),f=air.File.documentsDirectory.resolvePath("cdocs/documentation_010.pdf"),h=air.File.documentsDirectory.resolvePath("cdocs");0===c?(h.exists||h.createDirectory(),f.exists||e.copyTo(f,!0),f.openWithDefaultApplication()):(-1===d.indexOf(parseInt(c,10),
0)&&(c=3201),abrirNuevaVentanaNativa("html/print/errorPDF.html",c.toString()+"|","applicationDirectory","utilidad"))}catch(g){a=g}finally{"ninguno"!==a?(protector.cerrar(),cambiarEstadoBotones("inicial"),notificarConHumanJS("\u00a1ATENCI\u00d3N!<BR />"+a,"error")):(clearTimeout(b),b=setTimeout(function(){protector.cerrar();cambiarEstadoBotones("inicial")},2E3))}}
function abrirNuevaVentanaNativa(a,b,c,d){var e=window.nativeWindow.x+28,f=window.nativeWindow.y+40,h=new air.NativeWindowInitOptions,g="";h.type="utilidad"===d?air.NativeWindowType.UTILITY:air.NativeWindowType.NORMAL;"applicationDirectory"===c?g=air.File.applicationDirectory.resolvePath(a).url:"applicationStorageDirectory"===c&&(g=air.File.applicationStorageDirectory.resolvePath(a).url);null!==b&&(g=g+"?"+b);a=new air.Rectangle(e,f,640,394);air.HTMLLoader.createRootWindow(!0,h,!1,a).load(new air.URLRequest(g))}
function eliminarArchivosResiduales(a){var b=[],c,d;if(0!==arguments.length){for(c=0;c<arguments.length;c++)b.push(arguments[c]);for(var e=0;e<b.length;e++)c=air.File.applicationStorageDirectory.resolvePath(b[e]),c.isDirectory&&(d=c.getDirectoryListing(),0<d.length?c.deleteDirectory(!0):c.deleteDirectory())}}function iniciar(){window.nativeWindow.visible||(window.nativeWindow.visible=!0);window.nativeWindow.activate()}
function salir(){procesandoActualizaciones||air.NativeApplication.nativeApplication.exit()}function cerrarTodasLasVentanas(a){if(procesandoActualizaciones)a.preventDefault();else for(contador=0;contador<air.NativeApplication.nativeApplication.openedWindows.length;contador++)0<contador&&air.NativeApplication.nativeApplication.openedWindows[contador].close()}
function registrarVersiones(){var a=air.File.applicationStorageDirectory.resolvePath("xml"),b=air.File.applicationDirectory.resolvePath("xml/version.xml"),c=air.File.applicationStorageDirectory.resolvePath("xml/version.xml"),d=!1,e=""!==propiedadesPrograma.versiones.larga?propiedadesPrograma.versiones.larga:"0.0.0",f="";a.exists||(a.createDirectory(),b.copyTo(c,!0));transferencia=new air.FileStream;transferencia.open(c,air.FileMode.READ);a=transferencia.readUTFBytes(transferencia.bytesAvailable);
transferencia.close();(f=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("current")[0].firstChild.nodeValue)&&""!==f&&e>f&&(transferencia=new air.FileStream,transferencia.open(c,air.FileMode.WRITE),transferencia.writeUTFBytes('<?xml version="1.0" encoding="utf-8"?>\n<version>\n<current>'+e+"</current>\n</version>"),transferencia.close(),d=!0);d&&notificarConHumanJS("\u00a1HOLA!<br />CDOCS "+propiedadesPrograma.versiones.larga,"normal",5E3);eliminarArchivosResiduales("update","pdf")}
function verRecursos(){var a=air.SourceViewer.getDefault();a.setup({defaultFile:["index.html"]});a.setup({exclude:"cdocs.exe Icon.icns mimetype alivePDF/alivepdflib alivePDF/assets swf db pdf css/font css/index-min.css css/humane-original-foog-min.css META-INF/signatures.xml META-INF/AIR/hash META-INF/AIR/es.foog.cdocs.air.directory META-INF/AIR/es.foog.cdocs.air.desktop META-INF/AIR/image32x32 META-INF/AIR/image128x128 META-INF/AIR/image48x48 META-INF/AIR/image16x16 js/AIRAliases-min.js js/AIRSourceViewer-min.js js/alivePDFgenerator-min.js js/alivePDFWrapper-min.js js/humane-min.js js/iban-min.js js/index-aux-min.js js/index-min.js js/iban-min.js".split(" ")});
a.viewSource()}
function comprobarActualizaciones(){if(internetDisponible){actualizacionesTarea="";propiedadesPrograma.versiones.actualizaciones="";propiedadesPrograma.versiones.actualizacionesMensaje="";propiedadesPrograma.versiones.actualizacionesError="";propiedadesPrograma.versiones.actualizacionesDisponibles=!1;propiedadesPrograma.versiones.actualizacionesAlmacenamiento="";propiedadesPrograma.versiones.actualizacionesRepositorio="";var a,b;protector.abrir();cambiarEstadoBotones("procesando");var c="ninguno",
d=[];clearTimeout(a);a=setTimeout(function(){solicitud=new XMLHttpRequest;solicitud.open("get",propiedadesPrograma.versiones.actualizacionesDescriptor,!1);solicitud.onreadystatechange=function(){4===solicitud.readyState&&(200===solicitud.status&&null!==solicitud.responseXML?(d[0]=solicitud.responseXML.getElementsByTagName("versionNumber")[0].firstChild.nodeValue,d[1]=solicitud.responseXML.getElementsByTagName("url")[0].firstChild.nodeValue,/^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/.test(d[0])||(c="512")):
c=null===solicitud.responseXML?"400":solicitud.status)};try{solicitud.send(null)}catch(a){"ninguno"!==c&&(c=a)}finally{"ninguno"!==c?(propiedadesPrograma.versiones.actualizaciones="&#160;&#160;?",propiedadesPrograma.versiones.actualizacionesMensaje="<p class='texto-centrado' style='margin-top:12px;'>No ha sido posible la b\u00fasqueda de actualizaciones ...<p>",propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+
documentarErrorAJAX(c)+"<span>"):(propiedadesPrograma.versiones.actualizaciones=d[0],propiedadesPrograma.versiones.actualizacionesRepositorio=d[1],propiedadesPrograma.versiones.larga<propiedadesPrograma.versiones.actualizaciones?(propiedadesPrograma.versiones.actualizacionesMensaje="<p class='texto-centrado'>Hay una nueva versi\u00f3n disponible.</p><p class='texto-centrado'>Pulsa el bot\u00f3n &#171;<span class='texto-falsa-negrita'>DESCARGAR</span>&#187; para iniciar el proceso de instalaci\u00f3n.</p>",
propiedadesPrograma.versiones.actualizacionesDisponibles=!0):propiedadesPrograma.versiones.larga>=propiedadesPrograma.versiones.actualizaciones&&(propiedadesPrograma.versiones.actualizacionesMensaje="<p class='texto-centrado' style='margin-top:2px;'>No hay nuevas versiones disponibles.</p><p class='texto-centrado'>La aplicaci\u00f3n est\u00e1 actualizada.</p>")),clearTimeout(b),b=setTimeout(function(){cargarFormulario("update")},1E3)}},1E3)}else notificarConHumanJS("No fue posible conectarse a Internet",
"normal",5E3)}
function descargarActualizaciones(){actualizacionesTarea="descarga";procesandoActualizaciones=!0;propiedadesPrograma.versiones.actualizacionesMensaje="";propiedadesPrograma.versiones.actualizacionesError="";propiedadesPrograma.versiones.actualizacionesAlmacenamiento="";var a="ninguno";try{propiedadesPrograma.versiones.actualizacionesPaquete=propiedadesPrograma.versiones.actualizacionesRepositorio.substr(propiedadesPrograma.versiones.actualizacionesRepositorio.lastIndexOf("/")+1,propiedadesPrograma.versiones.actualizacionesRepositorio.length);document.getElementById("paquete-download").innerHTML=
propiedadesPrograma.versiones.actualizacionesPaquete;var b=new air.URLRequest(propiedadesPrograma.versiones.actualizacionesRepositorio);transferencia=new air.URLStream;matrizBytes=new air.ByteArray;transferencia.addEventListener(air.ProgressEvent.PROGRESS,function(a){var b=Math.round(a.bytesLoaded);a=Math.round(a.bytesTotal);propiedadesPrograma.versiones.actualizacionesPeso=a;document.getElementById("peso-download").innerHTML=" ("+(propiedadesPrograma.versiones.actualizacionesPeso/1E6).toFixed(2)+
" MB)";visualizarProgreso(b,a,!1)});transferencia.addEventListener(air.Event.COMPLETE,guardarActualizaciones);transferencia.load(b);transferencia.addEventListener(air.IOErrorEvent.IO_ERROR,function(a){actualizacionesTarea="";procesandoActualizaciones=!1;propiedadesPrograma.versiones.actualizacionesMensaje="<span>Se ha producido un error ...<span>";propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+
documentarErrorAJAX(a.text)+"<span>";document.getElementById("mensaje-download").innerHTML=propiedadesPrograma.versiones.actualizacionesMensaje;document.getElementById("alerta-download").innerHTML=propiedadesPrograma.versiones.actualizacionesError})}catch(c){a=c}finally{"ninguno"!==a&&(actualizacionesTarea="",procesandoActualizaciones=!1,propiedadesPrograma.versiones.actualizacionesMensaje="<span>Se ha producido un error ...<span>",propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+
documentarErrorAJAX(a)+"<span>",document.getElementById("mensaje-download").innerHTML=propiedadesPrograma.versiones.actualizacionesMensaje,document.getElementById("alerta-download").innerHTML=propiedadesPrograma.versiones.actualizacionesError)}}
function cancelarDescargaActualizaciones(){cambiarEstadoBotones("procesando");actualizacionesTarea="";procesandoActualizaciones=!1;transferencia.close();propiedadesPrograma.versiones.actualizacionesMensaje="&#160;";propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>Descarga cancelada. Pulsa el bot\u00f3n &#171;INICIO&#187; para continuar.";document.getElementById("mensaje-download").innerHTML=
propiedadesPrograma.versiones.actualizacionesMensaje;document.getElementById("alerta-download").innerHTML=propiedadesPrograma.versiones.actualizacionesError;eliminarArchivosResiduales("update");var a;clearTimeout(a);a=setTimeout(function(){cambiarEstadoBotones("descarga-cancelada")},500)}
function guardarActualizaciones(a){ventanaPrincipalMinimizada&&window.nativeWindow.restore();actualizacionesTarea="";cambiarEstadoBotones("procesando");window.nativeWindow.title="CDOCS : ACTUALIZACIONES - ALMACENAMIENTO";propiedadesPrograma.versiones.actualizacionesMensaje="";propiedadesPrograma.versiones.actualizacionesError="";a="ninguno";try{document.getElementById("tarea-download").innerHTML="Guardando";eliminarArchivosResiduales("update");var b=air.File.applicationStorageDirectory.resolvePath("update");
b.exists||b.createDirectory();transferencia.readBytes(matrizBytes,0,transferencia.bytesAvailable);propiedadesPrograma.versiones.actualizacionesAlmacenamiento=air.File.applicationStorageDirectory.resolvePath("update/"+propiedadesPrograma.versiones.actualizacionesPaquete);var c=new air.FileStream;c.open(propiedadesPrograma.versiones.actualizacionesAlmacenamiento,air.FileMode.WRITE);c.writeBytes(matrizBytes,0,matrizBytes.length);c.close();transferencia.addEventListener(air.IOErrorEvent.IO_ERROR,function(a){procesandoActualizaciones=
!1;cambiarEstadoBotones("inicial");propiedadesPrograma.versiones.actualizacionesMensaje="<span>Se ha producido un error ...<span>";propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+documentarErrorAJAX(a.text)+"<span>";document.getElementById("mensaje-download").innerHTML=propiedadesPrograma.versiones.actualizacionesMensaje;document.getElementById("alerta-download").innerHTML=
propiedadesPrograma.versiones.actualizacionesError})}catch(d){a=d}finally{"ninguno"!==a?(procesandoActualizaciones=!1,cambiarEstadoBotones("inicial"),propiedadesPrograma.versiones.actualizacionesMensaje="<span>Se ha producido un error ...<span>",propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+documentarErrorAJAX(a)+"<span>",document.getElementById("mensaje-download").innerHTML=
propiedadesPrograma.versiones.actualizacionesMensaje,document.getElementById("alerta-download").innerHTML=propiedadesPrograma.versiones.actualizacionesError):visualizarProgreso(parseInt(document.getElementById("progreso-download").style.width,10),85,!0,"comprobarInstalador")}}
function comprobarInstalador(){ventanaPrincipalMinimizada&&window.nativeWindow.restore();actualizacionesTarea="";cambiarEstadoBotones("procesando");window.nativeWindow.title="CDOCS : ACTUALIZACIONES - TEST";propiedadesPrograma.versiones.actualizacionesMensaje="";propiedadesPrograma.versiones.actualizacionesError="";var a="ninguno";document.getElementById("tarea-download").innerHTML="Verificando";try{propiedadesPrograma.versiones.actualizacionesAlmacenamiento.exists?propiedadesPrograma.versiones.actualizacionesAlmacenamiento.size!==
propiedadesPrograma.versiones.actualizacionesPeso&&(a="Installer Package size different than expected"):a="There is no Installer Package in the specified path"}catch(b){a=b}finally{"ninguno"!==a?(procesandoActualizaciones=!1,cambiarEstadoBotones("inicial"),propiedadesPrograma.versiones.actualizacionesMensaje="<span>Se ha producido un error ...<span>",propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+
a+"<span>",document.getElementById("mensaje-download").innerHTML=propiedadesPrograma.versiones.actualizacionesMensaje,document.getElementById("alerta-download").innerHTML=propiedadesPrograma.versiones.actualizacionesError):visualizarProgreso(parseInt(document.getElementById("progreso-download").style.width,10),99,!0,"instalarActualizaciones")}}
function instalarActualizaciones(){ventanaPrincipalMinimizada&&window.nativeWindow.restore();actualizacionesTarea="";cambiarEstadoBotones("procesando");window.nativeWindow.title="CDOCS : ACTUALIZACIONES - INSTALACI\u00d3N";propiedadesPrograma.versiones.actualizacionesMensaje="Instalando <span class='texo-capital'>CDOCS</span> (nueva versi\u00f3n  <span class='texo-capital'>"+propiedadesPrograma.versiones.actualizaciones+"</span>)";propiedadesPrograma.versiones.actualizacionesError="";document.getElementById("tarea-download").innerHTML=
"";document.getElementById("mensaje-download").innerHTML=propiedadesPrograma.versiones.actualizacionesMensaje;var a="ninguno";clearTimeout(void 0);setTimeout(function(){document.getElementById("progreso-download").style.width="448px";document.getElementById("porcentaje-download").innerHTML="100";try{air.Capabilities.isDebugger?(procesandoActualizaciones=!1,a="Error: It is not allowed to install updates in debug mode"):(new air.Updater).update(propiedadesPrograma.versiones.actualizacionesAlmacenamiento,
propiedadesPrograma.versiones.actualizaciones)}catch(b){a=b}finally{procesandoActualizaciones=!1,"ninguno"!==a&&(document.getElementById("progreso-download").style.width="444px",document.getElementById("porcentaje-download").innerHTML="99",propiedadesPrograma.versiones.actualizacionesMensaje="<span>Se ha producido un error ...<span>",propiedadesPrograma.versiones.actualizacionesError="<span><img src='images/alerta.png' alt='' title='' class='alerta-imagen-error'></span><span class='alerta-texto-error'>"+
a+"<span>",document.getElementById("tarea-download").innerHTML="Instalando",document.getElementById("mensaje-download").innerHTML=propiedadesPrograma.versiones.actualizacionesMensaje,document.getElementById("alerta-download").innerHTML=propiedadesPrograma.versiones.actualizacionesError,cambiarEstadoBotones("inicial"),"Error: It is not allowed to install updates in debug mode"===a&&notificarConHumanJS("\u00a1ATENCI\u00d3N!<br />No est\u00e1 permitido instalar actualizaciones en modo depuraci\u00f3n.<br />(lanzamiento desde ADL)",
"error",5E3))}},1E3)}
function visualizarProgreso(a,b,c,d){d=d||null;var e=document.getElementById("progreso-download"),f=document.getElementById("porcentaje-download"),h=0,g=448,k,l=0;c?(h=a,e.style.width=h+"px",l=parseInt(f.innerHTML,10),k=setInterval(function(){l+=1;if(l<=b)h=g*l/100,e.style.width=h+"px",f.innerHTML=Math.round(l);else if(clearInterval(k),null!==d){var a=d;"comprobarInstalador"===a?comprobarInstalador():"instalarActualizaciones"===a&&instalarActualizaciones()}},200)):(g=Math.round(69*g/100),l=a/b*69,
f.innerHTML=Math.round(l),h=a/b*g,e.style.width=h+"px")}
window.onload=function(){window.htmlLoader.cacheResponse=!1;window.htmlLoader.useCache=!1;precargarImagen();window.nativeWindow.x=parseInt(air.Screen.mainScreen.bounds.width/2-window.nativeWindow.width/2,10);window.nativeWindow.y=parseInt(air.Screen.mainScreen.bounds.height/2-window.nativeWindow.height/2,10);fechaSistema=new obtenerFecha;obtenerPropiedadesPrograma();obtenerNombreComercialSO();mnuEmergente=construirMnuEmergente();cargarFormulario("home");activarMnuIcono();monitorizarInternet();registrarVersiones();
document.oncontextmenu=function(){return!1};window.nativeWindow.addEventListener(air.Event.CLOSING,cerrarTodasLasVentanas);mnuEmergente.addEventListener("preparing",function(a){a.preventDefault();cambiarEstadoBotones("mnu-inactivo")},!1);document.getElementById("cabecera").addEventListener("click",function(){"botones-inactivo"===document.getElementById("botones-mnu").className&&cambiarEstadoBotones("mnu-activo")},!1);document.getElementById("continente").addEventListener("click",function(){"botones-inactivo"===
document.getElementById("botones-mnu").className&&cambiarEstadoBotones("mnu-activo")},!1);document.addEventListener("keydown",capturarPulsacionesTeclado,!1);window.nativeWindow.addEventListener(air.NativeWindowDisplayStateEvent.DISPLAY_STATE_CHANGE,function(a){a.preventDefault();a.afterDisplayState===air.NativeWindowDisplayState.MINIMIZED?ventanaPrincipalMinimizada=!0:a.afterDisplayState===air.NativeWindowDisplayState.NORMAL&&(ventanaPrincipalMinimizada=!1)})};
